### PR TITLE
Change the container name to just "scraper"

### PR DESCRIPTION
**Pull request by pboothe**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/scraper/48)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/48#-:-Kl0-oiBdVtFfPkTzYKx:bnfp4nl)*

**Comment by stephen-soltesz** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/48)*

**Comment by stephen-soltesz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[k8s/deploy_template.yml, line 36 at r1](https://reviewable.io:443/reviews/m-lab/scraper/48#-Kl00QP_btUBVxFh5oGZ:-Kl00QP_btUBVxFh5oG_:b-ck4r02) ([raw file](https://github.com/m-lab/scraper/blob/f2ef1b671fe4c3c8b0fc99c47b9634b8eecfc84a/k8s/deploy_template.yml#L36)):*
> ```YAML
>       name: {{site_safe}}-{{node_safe}}-{{experiment_safe}}-{{rsync_module_safe}}
>       labels:
>         app: {{site_safe}}-{{node_safe}}-{{experiment_safe}}-{{rsync_module_safe}}
> ```

I think it will be helpful to have a category label at the deployment level also.

Maybe app=scraper would work.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/48)*

**Comment by pboothe** [comment]
PTAL

**Comment by stephen-soltesz** [comment]
Thank you. LGTM

**Pull request merged**
