### PR TITLE
rsync file list is more robust.

### PR DESCRIPTION
**Pull request by pboothe**
Disappearing ephemeral files can break the file listing operation as
well.  Don't let them.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/scraper/61)

### CODE REVIEW

**Comment by pboothe** [comment]
PTAL, as this has changed and now works to solve the problem in practice. In particular, this code has been running overnight scraping syd01 and has not (yet) failed.

**Comment by stephen-soltesz** [comment]
:+1: :lgtm: one suggestion for incremental log status.

---

Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[scraper.py, line 143 at r6](https://reviewable.io:443/reviews/m-lab/scraper/61#-Km9yzc2wWsDZhl2obDY:-Km9yzc2wWsDZhl2obDZ:b7pa64i) ([raw file](https://github.com/m-lab/scraper/blob/7aa63cd34774e20f29a0ed29e441e1709f87cab2/scraper.py#L143)):*
> ```Python
>     Args:
>       rsync_binary: the full path location of rsync
>       rsync_url: the rsync:// url to download the list from
> ```

destination is now an arg.

---

*[scraper.py, line 201 at r6](https://reviewable.io:443/reviews/m-lab/scraper/61#-KmA0XsiYcSACJNLpZ5R:-KmA0XsiYcSACJNLpZ5S:bpaokyc) ([raw file](https://github.com/m-lab/scraper/blob/7aa63cd34774e20f29a0ed29e441e1709f87cab2/scraper.py#L201)):*
> ```Python
>                 line = line[:-len(' is uptodate')]
>             files.append(line)
>         if len(files) % 1000 == 0:
> ```

I really like the idea of status messages here, especially after my experience this week. Though some servers easily have 250k files per day. My thought is that seeing small increments of progress initially is really valuable especially for servers that have severe delays, and that subsequent messages are helpful to see that something is happening. Maybe exponentially fewer each log line could be a nice balance between status frequency and log volume.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/61#-:-KmA89XYNtaX5KFdEHu5:b-rwe4wc)*

**Comment by stephen-soltesz** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r11, 1 of 1 files at r12.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[scraper.py, line 199 at r11](https://reviewable.io:443/reviews/m-lab/scraper/61#-KmDWMy5JfJzUOQxyy5f:-KmDWMy5JfJzUOQxyy5g:b-vgzz29) ([raw file](https://github.com/m-lab/scraper/blob/89869edd0c6f8179fd89769956a0a9ba7f345bf8/scraper.py#L199)):*
> ```Python
>     # -n causes the whole thing to run in dry-run mode
>     # -vv causes the debug output which we parse
>     command = ([rsync_binary, '-n', '-vv'] +
> ```

Not an imperative, just wanted to share my joy. I love long options because they obviate the need for many comments and usually self-describe. e.g. `--dry-run`. That would be weird for `-vv` though, but that's in the class of "universally recognizable" imo.

---

*[scraper.py, line 865 at r11](https://reviewable.io:443/reviews/m-lab/scraper/61#-KmDYvhzwoexCaJjraTR:-KmDYvi-0_24z-62qRT4:b-c9w4pp) ([raw file](https://github.com/m-lab/scraper/blob/89869edd0c6f8179fd89769956a0a9ba7f345bf8/scraper.py#L865)):*
> ```Python
>         else:
>             # There is a timestamp, but the file is too new.
>             logging.debug('%s is too recent a file to download', name)
> ```

Is debug disabled by default? Imagining these will be plentiful.

---

*[scraper_test.py, line 51 at r12](https://reviewable.io:443/reviews/m-lab/scraper/61#-KmDZese2Qy-oBtvOwDq:-KmDZese2Qy-oBtvOwDr:b-2takih) ([raw file](https://github.com/m-lab/scraper/blob/2256234e0c661be4206bcc131c78d5c5e34af845/scraper_test.py#L51)):*
> ```Python
>         for i in range(100):
>             if i in (0, 1, 2, 4, 8, 16, 32, 64):
>                 self.assertTrue(scraper.has_one_bit_set_or_is_zero(i), i)
> ```

assertTrue / assertFalse take one argument. I'm not sure that happens with the second argument. Typo?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/61#-:-KmD_U9xWy7KeifuvveP:bnfp4nl)*

**Comment by pboothe** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[scraper.py, line 143 at r6](https://reviewable.io:443/reviews/m-lab/scraper/61#-Km9yzc2wWsDZhl2obDY:-KmDlRxodcqa2VIuo-7b:b-896fix) ([raw file](https://github.com/m-lab/scraper/blob/7aa63cd34774e20f29a0ed29e441e1709f87cab2/scraper.py#L143)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

destination is now an arg.
</blockquote></details>

Done.

---

*[scraper.py, line 201 at r6](https://reviewable.io:443/reviews/m-lab/scraper/61#-KmA0XsiYcSACJNLpZ5R:-KmDlbihPkqCcWo_JJNf:b-896fix) ([raw file](https://github.com/m-lab/scraper/blob/7aa63cd34774e20f29a0ed29e441e1709f87cab2/scraper.py#L201)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I really like the idea of status messages here, especially after my experience this week. Though some servers easily have 250k files per day. My thought is that seeing small increments of progress initially is really valuable especially for servers that have severe delays, and that subsequent messages are helpful to see that something is happening. Maybe exponentially fewer each log line could be a nice balance between status frequency and log volume.
</blockquote></details>

Done.

---

*[scraper.py, line 199 at r11](https://reviewable.io:443/reviews/m-lab/scraper/61#-KmDWMy5JfJzUOQxyy5f:-KmDlT86X9PKGP4CCdAm:bqdfegb) ([raw file](https://github.com/m-lab/scraper/blob/89869edd0c6f8179fd89769956a0a9ba7f345bf8/scraper.py#L199)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Not an imperative, just wanted to share my joy. I love long options because they obviate the need for many comments and usually self-describe. e.g. `--dry-run`. That would be weird for `-vv` though, but that's in the class of "universally recognizable" imo.
</blockquote></details>

Trying to precisely mirror the magic path makes me nervous about using long options.

---

*[scraper.py, line 865 at r11](https://reviewable.io:443/reviews/m-lab/scraper/61#-KmDYvhzwoexCaJjraTR:-KmDlcWPGo1MeGidPv-5:bb77ufg) ([raw file](https://github.com/m-lab/scraper/blob/89869edd0c6f8179fd89769956a0a9ba7f345bf8/scraper.py#L865)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Is debug disabled by default? Imagining these will be plentiful.
</blockquote></details>

Yes.

---

*[scraper_test.py, line 51 at r12](https://reviewable.io:443/reviews/m-lab/scraper/61#-KmDZese2Qy-oBtvOwDq:-KmDleBkp9-2F35FceHv:b-sp8pwy) ([raw file](https://github.com/m-lab/scraper/blob/2256234e0c661be4206bcc131c78d5c5e34af845/scraper_test.py#L51)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

assertTrue / assertFalse take one argument. I'm not sure that happens with the second argument. Typo?
</blockquote></details>

The second argument is the output message. This means that here it would (and did, when I had a typo) print out the number I got wrong.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/61)*

**Pull request merged**
