### PR TITLE
Productionizing scraper and adding prometheus monitoring.

### PR DESCRIPTION
**Pull request by pboothe**
Makes the scraper more monitorable.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/scraper/12)

### CODE REVIEW

**Comment by pboothe** [comment]
This also solves issue #11

**Comment by stephen-soltesz** [comment]
Reviewed 2 of 7 files at r1, 2 of 4 files at r3, 1 of 2 files at r5, 1 of 2 files at r6, 1 of 1 files at r7.
Review status: 7 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[deploy.yml, line 1 at r7](https://reviewable.io:443/reviews/m-lab/scraper/12#-KctC_G3Y4_RQmNqwjLJ:-KctC_G3Y4_RQmNqwjLK:by1zuu4) ([raw file](https://github.com/m-lab/scraper/blob/17668c459159eb677a9459a0ea07c1de29c2e5e9/deploy.yml#L1)):*
> ```YAML
> kind: Deployment
> ```

The current prometheus service discovery configuration chooses services based on whether or not they have an annotation. Specifically:

    prometheus.io/scrape = true

https://github.com/m-lab/prometheus-support/blob/master/prometheus.yml#L134

Is it possible to add annotations to this config file? I imagine this being very convenient and would make the config "prometheus ready". Or, is there a reason not to do this here, and make that a separate pre-deploy step?

---

*[README.md, line 24 at r7](https://reviewable.io:443/reviews/m-lab/scraper/12#-KctFoxE1J8sAGXr-tha:-KctFoxFedpcOuR43ZDM:bms4ym) ([raw file](https://github.com/m-lab/scraper/blob/17668c459159eb677a9459a0ea07c1de29c2e5e9/README.md#L24)):*
> ```Markdown
> ```
> 
> If you would like to run things on your own cluster, then you'll need to use scripts from the operator repository to fill in `deploy.yml`. You will also, of course, need your own cluster!  I created the cluster in staging with the following command line:
> ```

nit: please line wrap where possible.

---

*[run_scraper.py, line 20 at r7](https://reviewable.io:443/reviews/m-lab/scraper/12#-KctGCY4GsRDW0oRTziP:-KctGCY4GsRDW0oRTziQ:b-1ekqd5) ([raw file](https://github.com/m-lab/scraper/blob/17668c459159eb677a9459a0ea07c1de29c2e5e9/run_scraper.py#L20)):*
> ```Python
> """This program runs the MLab scraper in a loop.
> 
> run-scraper.py is intended to be the CMD for the docker container in which the
> ```

nit: run_scraper.py

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/12)*

**Comment by pboothe** [comment]
Review status: 4 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[deploy.yml, line 1 at r7](https://reviewable.io:443/reviews/m-lab/scraper/12#-KctC_G3Y4_RQmNqwjLJ:-KctPtNZRZz-yuxf4lJf:b-3lqan7) ([raw file](https://github.com/m-lab/scraper/blob/17668c459159eb677a9459a0ea07c1de29c2e5e9/deploy.yml#L1)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

The current prometheus service discovery configuration chooses services based on whether or not they have an annotation. Specifically:

    prometheus.io/scrape = true

https://github.com/m-lab/prometheus-support/blob/master/prometheus.yml#L134

Is it possible to add annotations to this config file? I imagine this being very convenient and would make the config "prometheus ready". Or, is there a reason not to do this here, and make that a separate pre-deploy step?
</blockquote></details>

Done (I think)

---

*[README.md, line 24 at r7](https://reviewable.io:443/reviews/m-lab/scraper/12#-KctFoxE1J8sAGXr-tha:-KctPxPfxQooJSKAD7po:b-896fix) ([raw file](https://github.com/m-lab/scraper/blob/17668c459159eb677a9459a0ea07c1de29c2e5e9/README.md#L24)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

nit: please line wrap where possible.
</blockquote></details>

Done.

---

*[run_scraper.py, line 20 at r7](https://reviewable.io:443/reviews/m-lab/scraper/12#-KctGCY4GsRDW0oRTziP:-KctPy44zMpW9W5xJ9uA:blcalj5) ([raw file](https://github.com/m-lab/scraper/blob/17668c459159eb677a9459a0ea07c1de29c2e5e9/run_scraper.py#L20)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

nit: run_scraper.py
</blockquote></details>

Done. Also deleted old text.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/12)*

**Comment by stephen-soltesz** [comment]
Reviewed 3 of 4 files at r8.
Review status: 7 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[deploy.yml, line 14 at r8](https://reviewable.io:443/reviews/m-lab/scraper/12#-KctSb_grU1nLI_ZQRHK:-KctSb_h7FN3nZbaG0dz:b-bjanfi) ([raw file](https://github.com/m-lab/scraper/blob/d0572b4b09ebbc2eaede438abb554356cbc5ab92/deploy.yml#L14)):*
> ```YAML
>     metadata:
>       annotations:
>         prometheus.io/scrape: 'true'
> ```

Does yaml do the right thing with quotes here? Or, the wrong thing without quotes?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/12)*

**Comment by stephen-soltesz** [comment]
Review status: 7 of 8 files reviewed at latest revision, 5 unresolved discussions.

---

*[run_scraper.py, line 50 at r8](https://reviewable.io:443/reviews/m-lab/scraper/12#-KcynaimH-0KUyoopVYr:-KcynaimH-0KUyoopVYs:bpe7neg) ([raw file](https://github.com/m-lab/scraper/blob/d0572b4b09ebbc2eaede438abb554356cbc5ab92/run_scraper.py#L50)):*
> ```Python
> # pylint: disable=no-value-for-parameter
> RSYNC_RUNS = prometheus_client.Histogram(
>     'rsync_run_time_seconds',
> ```

Sorry for missing this originally. I suggest preserving the `scraper_` prefix on all custom metrics reported by this exporter.

https://prometheus.io/docs/practices/naming/

In particular, I'm imaging a future where we want to be able to discover the metrics associated with a service while staying in prometheus and after we add more and more services (and metrics) over time.

Today, while playing with the staging setup, I expected to find all these buckets under the `scraper_` prefix, but I needed to go back to the source to figure out what the rsync run time bucket name was.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/12)*

**Comment by pboothe** [comment]
This PR has metastasized. Cutting it up into #13 and #14 and closing this too-big one.

**Pull request closed without merging**
