### PR TITLE
Add monitoring

### PR DESCRIPTION
**Pull request by pboothe**
Add monitoring and make the python process long-lived. This PR looks much bigger than it is because of a large code move of argument parsing from `scraper.py` to `run_scraper.py`.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/scraper/14)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
Reviewed 3 of 6 files at r1.
Review status: 3 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[scraper.py, line 437 at r1](https://reviewable.io:443/reviews/m-lab/scraper/14#-Kee7UjJydLJ-L8pwZ82:-Kee7UjJydLJ-L8pwZ83:b-bf8bj3) ([raw file](https://github.com/m-lab/scraper/blob/ab247f07ca86744d0ac837098c32d3fc8286ef6f/scraper.py#L437)):*
> ```Python
>     response = None
>     while response is None:
>         progress, response = request.next_chunk()
> ```

It looks like `next_chunk` can raise `HttpError` exceptions:
 https://developers.google.com/api-client-library/python/guide/media_upload

How do we want scraper to handle exceptions of this type? Right now it looks like `run_scraper.py` would exit. Should `SCRAPER_SUCCESS` count these exceptions also? What happens if a file is partially uploaded and the retry begins?

---

*[scraper.py, line 686 at r1](https://reviewable.io:443/reviews/m-lab/scraper/14#-Kee9YJN5IkwwyTfLZ8L:-Kee9YJN5IkwwyTfLZ8M:b-vp8m3s) ([raw file](https://github.com/m-lab/scraper/blob/ab247f07ca86744d0ac837098c32d3fc8286ef6f/scraper.py#L686)):*
> ```Python
>     new_high_water_mark = max_new_high_water_mark()
>     for day in find_all_days_to_upload(destination, new_high_water_mark):
>         mtime = None
> ```

I suggest calling this `max_mtime` to make the logic clearer. I needed to lookup `create_temporary_tarfiles` to understand that it always returns the latest mtime seen so far, and that it's correct for the condition 8 lines below to use the last mtime returned by `create_temporary_tarfiles`.

---

*[scraper_test.py, line 593 at r1](https://reviewable.io:443/reviews/m-lab/scraper/14#-KeeDntzIx2WcGFEdjfW:-KeeDntzIx2WcGFEdjfX:b-twy4pw) ([raw file](https://github.com/m-lab/scraper/blob/ab247f07ca86744d0ac837098c32d3fc8286ef6f/scraper_test.py#L593)):*
> ```Python
>         # the python compiler.  Then, in order to not trigger the "unused
>         # import" linter message, we should verify something about run_scraper.
>         self.assertNotEqual(run_scraper.__doc__, None)
> ```

I suggest using `assertIsNotNone(run_scraper.__doc__)`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/14)*

**Comment by pboothe** [comment]
Review status: 3 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[scraper.py, line 437 at r1](https://reviewable.io:443/reviews/m-lab/scraper/14#-Kee7UjJydLJ-L8pwZ82:-KeeHdKBVgbdrXtjo5Bw:b-5uoglo) ([raw file](https://github.com/m-lab/scraper/blob/ab247f07ca86744d0ac837098c32d3fc8286ef6f/scraper.py#L437)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

It looks like `next_chunk` can raise `HttpError` exceptions:
 https://developers.google.com/api-client-library/python/guide/media_upload

How do we want scraper to handle exceptions of this type? Right now it looks like `run_scraper.py` would exit. Should `SCRAPER_SUCCESS` count these exceptions also? What happens if a file is partially uploaded and the retry begins?
</blockquote></details>

Run_scraper now catches it and the raise is noted. When this happens, the file(and the rest of the files for that day) will be uploaded the next run through, overwriting any partial files.

---

*[scraper.py, line 686 at r1](https://reviewable.io:443/reviews/m-lab/scraper/14#-Kee9YJN5IkwwyTfLZ8L:-KeeIDVXeAciEWrniFxF:b-896fix) ([raw file](https://github.com/m-lab/scraper/blob/ab247f07ca86744d0ac837098c32d3fc8286ef6f/scraper.py#L686)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I suggest calling this `max_mtime` to make the logic clearer. I needed to lookup `create_temporary_tarfiles` to understand that it always returns the latest mtime seen so far, and that it's correct for the condition 8 lines below to use the last mtime returned by `create_temporary_tarfiles`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/14)*

**Comment by pboothe** [comment]
*[scraper_test.py, line 593 at r1](https://reviewable.io:443/reviews/m-lab/scraper/14#-KeeDntzIx2WcGFEdjfW:-KeeIgappZI59btqCmAn:b-896fix) ([raw file](https://github.com/m-lab/scraper/blob/ab247f07ca86744d0ac837098c32d3fc8286ef6f/scraper_test.py#L593)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I suggest using `assertIsNotNone(run_scraper.__doc__)`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/14)*

**Comment by stephen-soltesz** [comment]
:lgtm:

Thanks. One general FYI about monitoring and another request for explicit module path for HttpError in the docstring.

---

Review status: 3 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[run_scraper.py, line 186 at r2](https://reviewable.io:443/reviews/m-lab/scraper/14#-KeeKP_bZaJKqvwdLTB8:-KeeKP_bZaJKqvwdLTB9:bp4i7fs) ([raw file](https://github.com/m-lab/scraper/blob/93091b2d4d2e75591bdf4718745413da39ce4514/run_scraper.py#L186)):*
> ```Python
>             # pylint: enable=no-member
>         except (SystemExit, AssertionError,
>                 googleapiclient.errors.HttpError) as error:
> ```

Just an FYI for monitoring other exception types not explicitly listed yet.

It turns out that that the kubernetes API does not expose pod states automatically, but there is a "state-metrics" exporter available. https://github.com/kubernetes/kube-state-metrics

My thinking is that we should add this to our kubernetes config and monitor (maybe alert) on `kube_pod_container_status_restarts`, and maybe some of the other states.

---

*[scraper.py, line 437 at r1](https://reviewable.io:443/reviews/m-lab/scraper/14#-Kee7UjJydLJ-L8pwZ82:-KeeKD6i5gnyI2e_E1Uw:b-89q77k) ([raw file](https://github.com/m-lab/scraper/blob/ab247f07ca86744d0ac837098c32d3fc8286ef6f/scraper.py#L437)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Run_scraper now catches it and the raise is noted. When this happens, the file(and the rest of the files for that day) will be uploaded the next run through, overwriting any partial files.
</blockquote></details>

Cool.

---

*[scraper.py, line 428 at r2](https://reviewable.io:443/reviews/m-lab/scraper/14#-KeeK2xbhZnuS1mf8wUD:-KeeK2xbhZnuS1mf8wUE:bb8upmb) ([raw file](https://github.com/m-lab/scraper/blob/93091b2d4d2e75591bdf4718745413da39ce4514/scraper.py#L428)):*
> ```Python
> 
>     Raises:
>       HttpError
> ```

To avoid ambiguity, please specify the canonical path name: `googleapiclient.errors.HttpError`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/14#-:-KeeLUIWXubhVA7w5E-n:b-n9j6i8)*

**Comment by pboothe** [comment]
Review status: 3 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[run_scraper.py, line 186 at r2](https://reviewable.io:443/reviews/m-lab/scraper/14#-KeeKP_bZaJKqvwdLTB8:-KeeMCPZ-f1Em6CcEgdW:b-81nlyc) ([raw file](https://github.com/m-lab/scraper/blob/93091b2d4d2e75591bdf4718745413da39ce4514/run_scraper.py#L186)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Just an FYI for monitoring other exception types not explicitly listed yet.

It turns out that that the kubernetes API does not expose pod states automatically, but there is a "state-metrics" exporter available. https://github.com/kubernetes/kube-state-metrics

My thinking is that we should add this to our kubernetes config and monitor (maybe alert) on `kube_pod_container_status_restarts`, and maybe some of the other states.
</blockquote></details>

SGTM.

---

*[scraper.py, line 437 at r1](https://reviewable.io:443/reviews/m-lab/scraper/14#-Kee7UjJydLJ-L8pwZ82:-KeeMJNF-otXiSS1e08u:b-dxo5k0) ([raw file](https://github.com/m-lab/scraper/blob/ab247f07ca86744d0ac837098c32d3fc8286ef6f/scraper.py#L437)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Cool.
</blockquote></details>

If I reply to this, then reviewable won't block merging.

---

*[scraper.py, line 428 at r2](https://reviewable.io:443/reviews/m-lab/scraper/14#-KeeK2xbhZnuS1mf8wUD:-KeeMI27eFsD2O01itzX:b-896fix) ([raw file](https://github.com/m-lab/scraper/blob/93091b2d4d2e75591bdf4718745413da39ce4514/scraper.py#L428)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

To avoid ambiguity, please specify the canonical path name: `googleapiclient.errors.HttpError`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/14)*

**Comment by pboothe** [comment]
One more try to clear out the Reviewable queue.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/14#-:-KeeMRmh6iJd8P5ITRLr:byl22kj)*

**Comment by stephen-soltesz** [comment]
This PR addresses issue https://github.com/m-lab/scraper/issues/11

**Pull request merged**
