### PR TITLE
Autodeploy to the staging cluster

### PR DESCRIPTION
**Pull request by pboothe**
Finally, it looks like scraper can autodeploy to the staging cluster.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/scraper/47)

### CODE REVIEW

**Comment by pboothe** [comment]
Build initially failed, but then I changed permissions again on the service account and the build succeeded. Check it out!

**Comment by stephen-soltesz** [comment]
Reviewed 7 of 12 files at r1.
Review status: 6 of 11 files reviewed at latest revision, 6 unresolved discussions.

---

*[.travis.yml, line 16 at r1](https://reviewable.io:443/reviews/m-lab/scraper/47#-KkrLgBPgzu8hfyTmpQD:-KkrLgBPgzu8hfyTmpQE:b-wdke4a) ([raw file](https://github.com/m-lab/scraper/blob/0a5ec1e2f7ef1b13a5ce8bd6d75baef0c1db8da3/.travis.yml#L16)):*
> ```YAML
> - pip install coveralls
> - $TRAVIS_BUILD_DIR/travis/install_gcloud.sh
> - yes | ${HOME}/google-cloud-sdk/bin/gcloud components install kubectl
> ```

Please remove `yes |`  in favor of `gcloud config set core/disable_prompts true`

---

*[k8s/claim.yml, line 1 at r1](https://reviewable.io:443/reviews/m-lab/scraper/47#-KkrT1hs6R-W7s5VB-qk:-KkrT1hs6R-W7s5VB-ql:bcx727y) ([raw file](https://github.com/m-lab/scraper/blob/0a5ec1e2f7ef1b13a5ce8bd6d75baef0c1db8da3/k8s/claim.yml#L1)):*
> ```YAML
> # This file is a template, to be fleshed out by running:
> ```

I like the convention of placing k8s configs in their own directory.

This file is a template, and I have mixed feelings about mixing two kinds of .yml files in the same directory.

Prometheus will soon have templates for config files, but not yet k8s configs. I don't have strong opinions about the mechanism.

Is there a different file name or location that could make the difference between a stand-alone k8s config and a k8s template clear?

---

*[k8s/deploy.sh, line 12 at r1](https://reviewable.io:443/reviews/m-lab/scraper/47#-KkrVRp6ZckkWM5Fanpv:-KkrVRp6ZckkWM5Fanpw:b116ng) ([raw file](https://github.com/m-lab/scraper/blob/0a5ec1e2f7ef1b13a5ce8bd6d75baef0c1db8da3/k8s/deploy.sh#L12)):*
> ```Shell
> source "${HOME}/google-cloud-sdk/path.bash.inc"
> 
> ssh-keygen -f ~/.ssh/google_compute_engine -N ""
> ```

Please remove this command or document why it is needed.

---

*[k8s/deploy.sh, line 30 at r1](https://reviewable.io:443/reviews/m-lab/scraper/47#-KkrTiPQXZJsJTc03xHw:-KkrTiPQXZJsJTc03xHx:b-ptkebm) ([raw file](https://github.com/m-lab/scraper/blob/0a5ec1e2f7ef1b13a5ce8bd6d75baef0c1db8da3/k8s/deploy.sh#L30)):*
> ```Shell
>     kubectl apply -f k8s/namespace.yml
>     kubectl apply -f k8s/storage-class.yml
>     kubectl apply -f claims/
> ```

I have mixed feelings about calling `kubectl apply` here and from a command at the end of `build_and_deploy_container.sh`.

Also, there are two calls to `gcloud container clusters get-credentials`.

Just like separating k8s configs from templates, I believe it would be clearer if the steps for scraper and/or scraper sync were:
 * generate configs from templates.
 * build container
 * kubectl apply configs

---

*[k8s/deploy.yml, line 34 at r1](https://reviewable.io:443/reviews/m-lab/scraper/47#-KkrQ5DOTLQPYEWAZQxX:-KkrQ5DPruB1EoAjHRAj:bivpy72) ([raw file](https://github.com/m-lab/scraper/blob/0a5ec1e2f7ef1b13a5ce8bd6d75baef0c1db8da3/k8s/deploy.yml#L34)):*
> ```YAML
>         prometheus.io/scrape: 'true'
>         prometheus.io/port: '9090'
>         prometheus.io/port2: '9100'
> ```

Hmm, I believe there is a new feature that exposes the port of each container during prom-service-discovery.
https://github.com/prometheus/docs/blob/master/content/docs/operating/configuration.md#pod

This convention is not used in our current or the reference configuraton for k8s service discovery.
https://github.com/prometheus/prometheus/blob/master/documentation/examples/prometheus-kubernetes.yml

But, seeing the new docs, I believe that we may create a new relabel config that uses the declared `containerPort`s.

For now, please:
* remove the `prometheus.io/port2: '9100'` label.
* add an explicit `containerPort` to the scraper container.

In the short term, we won't get the node exporter data, but since we have dedicated disk space now, I'm not as worried right away. And, since this is a prometheus config, it should be changeable largely independent of scraper. Or, with auto-deploy, this should still be straight forward to update in the future.

---

*[k8s/fill_in_templates.sh, line 16 at r1](https://reviewable.io:443/reviews/m-lab/scraper/47#-KkrXHIOCdyNlyR2stE4:-KkrWjH1JAWRPftLBrCw:blrcz7x) ([raw file](https://github.com/m-lab/scraper/blob/0a5ec1e2f7ef1b13a5ce8bd6d75baef0c1db8da3/k8s/fill_in_templates.sh#L16)):*
> ```Shell
> 
> # claims/ is also referenced in deploy.sh
> mkdir -p claims
> ```

It looks like deploy.sh is the main entry point. Rather than use constants across scripts, please pass these targets as parameters. This way, the specific names "claims" and "deployment" only need to be referenced from `deploy.sh`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/47)*

**Comment by pboothe** [comment]
Review status: 4 of 11 files reviewed at latest revision, 6 unresolved discussions.

---

*[.travis.yml, line 16 at r1](https://reviewable.io:443/reviews/m-lab/scraper/47#-KkrLgBPgzu8hfyTmpQD:-KkvoxSTF-4T1ZMF3M__:b-896fix) ([raw file](https://github.com/m-lab/scraper/blob/0a5ec1e2f7ef1b13a5ce8bd6d75baef0c1db8da3/.travis.yml#L16)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please remove `yes |`  in favor of `gcloud config set core/disable_prompts true`
</blockquote></details>

Done.

---

*[k8s/claim_template.yml, line 1 at r1](https://reviewable.io:443/reviews/m-lab/scraper/47#-KkrT1hs6R-W7s5VB-qk:-KkvoygAqvH-_a69_87i:b-896fix) ([raw file](https://github.com/m-lab/scraper/blob/0a5ec1e2f7ef1b13a5ce8bd6d75baef0c1db8da3/k8s/claim_template.yml#L1)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I like the convention of placing k8s configs in their own directory.

This file is a template, and I have mixed feelings about mixing two kinds of .yml files in the same directory.

Prometheus will soon have templates for config files, but not yet k8s configs. I don't have strong opinions about the mechanism.

Is there a different file name or location that could make the difference between a stand-alone k8s config and a k8s template clear?
</blockquote></details>

Done.

---

*[k8s/deploy_template.yml, line 34 at r1](https://reviewable.io:443/reviews/m-lab/scraper/47#-KkrQ5DOTLQPYEWAZQxX:-Kkvp-FM7dWjDmtarp_0:b-896fix) ([raw file](https://github.com/m-lab/scraper/blob/0a5ec1e2f7ef1b13a5ce8bd6d75baef0c1db8da3/k8s/deploy_template.yml#L34)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Hmm, I believe there is a new feature that exposes the port of each container during prom-service-discovery.
https://github.com/prometheus/docs/blob/master/content/docs/operating/configuration.md#pod

This convention is not used in our current or the reference configuraton for k8s service discovery.
https://github.com/prometheus/prometheus/blob/master/documentation/examples/prometheus-kubernetes.yml

But, seeing the new docs, I believe that we may create a new relabel config that uses the declared `containerPort`s.

For now, please:
* remove the `prometheus.io/port2: '9100'` label.
* add an explicit `containerPort` to the scraper container.

In the short term, we won't get the node exporter data, but since we have dedicated disk space now, I'm not as worried right away. And, since this is a prometheus config, it should be changeable largely independent of scraper. Or, with auto-deploy, this should still be straight forward to update in the future.
</blockquote></details>

Done.

---

*[k8s/deploy.sh, line 12 at r1](https://reviewable.io:443/reviews/m-lab/scraper/47#-KkrVRp6ZckkWM5Fanpv:-Kkvp1bkYy5VLi9e82Ws:b-896fix) ([raw file](https://github.com/m-lab/scraper/blob/0a5ec1e2f7ef1b13a5ce8bd6d75baef0c1db8da3/k8s/deploy.sh#L12)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please remove this command or document why it is needed.
</blockquote></details>

Done.

---

*[k8s/deploy.sh, line 30 at r1](https://reviewable.io:443/reviews/m-lab/scraper/47#-KkrTiPQXZJsJTc03xHw:-Kkvp1-AIOV69axVMaZ-:b-896fix) ([raw file](https://github.com/m-lab/scraper/blob/0a5ec1e2f7ef1b13a5ce8bd6d75baef0c1db8da3/k8s/deploy.sh#L30)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I have mixed feelings about calling `kubectl apply` here and from a command at the end of `build_and_deploy_container.sh`.

Also, there are two calls to `gcloud container clusters get-credentials`.

Just like separating k8s configs from templates, I believe it would be clearer if the steps for scraper and/or scraper sync were:
 * generate configs from templates.
 * build container
 * kubectl apply configs
</blockquote></details>

Done.

---

*[k8s/fill_in_templates.sh, line 16 at r1](https://reviewable.io:443/reviews/m-lab/scraper/47#-KkrXHIOCdyNlyR2stE4:-Kkvp2o_B-YEJVh-Nwr6:b-896fix) ([raw file](https://github.com/m-lab/scraper/blob/0a5ec1e2f7ef1b13a5ce8bd6d75baef0c1db8da3/k8s/fill_in_templates.sh#L16)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

It looks like deploy.sh is the main entry point. Rather than use constants across scripts, please pass these targets as parameters. This way, the specific names "claims" and "deployment" only need to be referenced from `deploy.sh`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/47)*

**Comment by stephen-soltesz** [comment]
:lgtm: Just some final tweaks.

---

Reviewed 6 of 11 files at r2.
Review status: 6 of 11 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[.travis.yml, line 20 at r4](https://reviewable.io:443/reviews/m-lab/scraper/47#-Kkw7kYMFKogVVnlKO4f:-Kkw7kYMFKogVVnlKO4g:b-g37dob) ([raw file](https://github.com/m-lab/scraper/blob/1ba8b73885e741d32ec3762b995872be6e6afc20/.travis.yml#L20)):*
> ```YAML
> deploy:
> - provider: script
>   script:  gcloud auth activate-service-account --key-file /tmp/staging-secret-key.json && cd $TRAVIS_BUILD_DIR && ./deploy.sh staging
> ```

Please move this logic to `deploy.sh`

---

*[deploy.sh, line 82 at r4](https://reviewable.io:443/reviews/m-lab/scraper/47#-KkwAuwptnfl9WIZ4DCH:-KkwAuwq1S_sFB0FbhN9:b50grtx) ([raw file](https://github.com/m-lab/scraper/blob/1ba8b73885e741d32ec3762b995872be6e6afc20/deploy.sh#L82)):*
> ```Shell
> fi
> 
> ./travis/substitute_values.sh deployment \
> ```

Please add simple comments about the work each major step performs in this sequence.

---

*[k8s/deploy_template.yml, line 34 at r1](https://reviewable.io:443/reviews/m-lab/scraper/47#-KkrQ5DOTLQPYEWAZQxX:-Kkw8I0u08K_2IzmAoY3:bz1u78q) ([raw file](https://github.com/m-lab/scraper/blob/0a5ec1e2f7ef1b13a5ce8bd6d75baef0c1db8da3/k8s/deploy_template.yml#L34)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

And, now thanks to https://github.com/m-lab/prometheus-support/pull/40 we can remove the the annotation for `prometheus.io/port: '9090'` also.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/47#-:-KkwB4MCHv0zuyPplxVQ:byyiqnq)*

**Comment by pboothe** [comment]
Review status: 5 of 11 files reviewed at latest revision, 3 unresolved discussions.

---

*[.travis.yml, line 20 at r4](https://reviewable.io:443/reviews/m-lab/scraper/47#-Kkw7kYMFKogVVnlKO4f:-KkwUC5kVsu0Gp9nIsqT:b-896fix) ([raw file](https://github.com/m-lab/scraper/blob/1ba8b73885e741d32ec3762b995872be6e6afc20/.travis.yml#L20)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please move this logic to `deploy.sh`
</blockquote></details>

Done.

---

*[deploy.sh, line 82 at r4](https://reviewable.io:443/reviews/m-lab/scraper/47#-KkwAuwptnfl9WIZ4DCH:-KkwUDESHzd_tRTXusP-:b-896fix) ([raw file](https://github.com/m-lab/scraper/blob/1ba8b73885e741d32ec3762b995872be6e6afc20/deploy.sh#L82)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please add simple comments about the work each major step performs in this sequence.
</blockquote></details>

Done.

---

*[k8s/deploy_template.yml, line 34 at r1](https://reviewable.io:443/reviews/m-lab/scraper/47#-KkrQ5DOTLQPYEWAZQxX:-KkwUFVWCeiJIxTiwXyP:b-896fix) ([raw file](https://github.com/m-lab/scraper/blob/0a5ec1e2f7ef1b13a5ce8bd6d75baef0c1db8da3/k8s/deploy_template.yml#L34)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

And, now thanks to https://github.com/m-lab/prometheus-support/pull/40 we can remove the the annotation for `prometheus.io/port: '9090'` also.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/47)*

**Pull request merged**
