### PR TITLE
Datastore download

### PR DESCRIPTION
**Pull request by pboothe**
The first half of the sync client.  Downloads data from datastore, does not (yet) update the spreadsheet.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/scraper/27)

### CODE REVIEW

**Comment by pboothe** [comment]
First part of addressing #28

**Comment by stephen-soltesz** [comment]
Hi, Peter,

This looks very nice. I've added some comments for what could be refinements. Nothing fundamental.

Best,
Stephen

---

Reviewed 5 of 7 files at r1.
Review status: 5 of 7 files reviewed at latest revision, 8 unresolved discussions.

---

*[sync/sync.py, line 25 at r1](https://reviewable.io:443/reviews/m-lab/scraper/27#-KgWIRXh5fbszZia9kW0:-KgWIRXh5fbszZia9kW1:bu660ur) ([raw file](https://github.com/m-lab/scraper/blob/081a53afd2c75dbd7179b59e7c3ee69ee049c16f/sync/sync.py#L25)):*
> scripts in charge of data deletion should read from cloud
> datastore directly.

This is what I was trying to express to you on the balcony the other day. I disagree that clients should read from datastore directly. Is this the long term migration we want?

---

*[sync/sync.py, line 29 at r1](https://reviewable.io:443/reviews/m-lab/scraper/27#-KgWIvLnhPSmQ6fzOqf7:-KgWIvLnhPSmQ6fzOqf8:blcx3oz) ([raw file](https://github.com/m-lab/scraper/blob/081a53afd2c75dbd7179b59e7c3ee69ee049c16f/sync/sync.py#L29)):*
> ```Python
> 
> This program needs to be run on a GCE instance that has access to the Sheets
> API  Sheets API access is not enabled by default for GCE, and it can't be
> ```

nit. missing period: "API  Sheets

---

*[sync/sync.py, line 129 at r1](https://reviewable.io:443/reviews/m-lab/scraper/27#-KgWLRvFEl1tNvnMSJR1:-KgWLRvFEl1tNvnMSJR2:b2zqtf4) ([raw file](https://github.com/m-lab/scraper/blob/081a53afd2c75dbd7179b59e7c3ee69ee049c16f/sync/sync.py#L129)):*
> ```Python
>     def do_GET(self):
>         """Print out the ground truth from cloud datastore as a webpage."""
>         logging.info('New request!')
> ```

What do you think of adding the remote IP here, to give an extra hint in the logs, just in case?

---

*[sync/sync.py, line 153 at r1](https://reviewable.io:443/reviews/m-lab/scraper/27#-KgWO1tKmZ3LeN2R0Yey:-KgWO1tKmZ3LeN2R0Yez:b-3wjr0b) ([raw file](https://github.com/m-lab/scraper/blob/081a53afd2c75dbd7179b59e7c3ee69ee049c16f/sync/sync.py#L153)):*
> ```Python
>         <body>
>           <table><tr>''')
>         data = get_fleet_data(WebHandler.namespace)
> ```

If something was funny with datastore, and the spreadsheet wasn't getting updated, and an operator came to visit this page to investigate, but `datastore_client.query` raised an exception (b/c datastore is funny) what would the operator see at this point?

---

*[sync/sync_test.py, line 75 at r1](https://reviewable.io:443/reviews/m-lab/scraper/27#-KgWQurFw23X-ZzC95Kk:-KgWQurFw23X-ZzC95Kl:b-6xnuqf) ([raw file](https://github.com/m-lab/scraper/blob/081a53afd2c75dbd7179b59e7c3ee69ee049c16f/sync/sync_test.py#L75)):*
> ```Python
>         with self.assertRaises(SystemExit):
>             with testfixtures.OutputCapture() as _:
>                 sync.parse_args(['-h'])
> ```

Optional: I really like the idea of testing whether a system has help text. How do we know if it worked vs the flag being unsupported?

---

*[sync/sync_test.py, line 90 at r1](https://reviewable.io:443/reviews/m-lab/scraper/27#-KgWXysx8clRUeue-sXq:-KgWXysx8clRUeue-sXr:bo7357q) ([raw file](https://github.com/m-lab/scraper/blob/081a53afd2c75dbd7179b59e7c3ee69ee049c16f/sync/sync_test.py#L90)):*
> ```Python
>         mock_datastore.Client.return_value = mock_client
>         mock_client.query().fetch.return_value = self.test_datastore_data
>         returned_answers = sync.get_fleet_data('scraper')
> ```

Where possible, separate "arrange", "act" and "assert" blocks separated by white space helps improve the readability of unit tests, by visually contrasting each block. Here and below, I found myself searching for the method under test a little more. What do you think of separating these blocks here and in the `do_get` tests?

---

*[sync/sync_test.py, line 115 at r1](https://reviewable.io:443/reviews/m-lab/scraper/27#-KgWSc6uT9Cu1HiCZ5hm:-KgWSc6uT9Cu1HiCZ5hn:bxc2frf) ([raw file](https://github.com/m-lab/scraper/blob/081a53afd2c75dbd7179b59e7c3ee69ee049c16f/sync/sync_test.py#L115)):*
> ```Python
>              u'lastcollectionattempt': 'x2017-03-29-15:46',
>              u'maxrawfilemtimearchived': ''}]
>         self.assertEqual(returned_answers, correct_answers)
> ```

`assertItemsEqual`? I think there's a difference in how the diff is reported when an error occurs that makes `assertItemsEqual` preferable. Can you confirm?

---

*[sync/sync_test.py, line 117 at r1](https://reviewable.io:443/reviews/m-lab/scraper/27#-KgWTNvBrzZ4X7Un43JD:-KgWTNvCRYC3f9cx3wuD:bp8r2ca) ([raw file](https://github.com/m-lab/scraper/blob/081a53afd2c75dbd7179b59e7c3ee69ee049c16f/sync/sync_test.py#L117)):*
> ```Python
>         self.assertEqual(returned_answers, correct_answers)
> 
>     @mock.patch.object(sync, 'datastore')
> ```

Since we're testing `do_GET` in this unit test, my bias would be toward mocking `get_fleet_data`. This strategy requires only shallow knowledge of the implementation, rather than two levels deep. This will be easier for `test_do_get_no_data` below. What do you think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/27#-:-KgWZ0JrXI9naZcWomi5:b-jqwsp8)*

**Comment by pboothe** [comment]
Review status: 5 of 7 files reviewed at latest revision, 8 unresolved discussions.

---

*[sync/sync.py, line 25 at r1](https://reviewable.io:443/reviews/m-lab/scraper/27#-KgWIRXh5fbszZia9kW0:-KgZTPjAJNch-LQCWxWZ:b-t6nkhb) ([raw file](https://github.com/m-lab/scraper/blob/081a53afd2c75dbd7179b59e7c3ee69ee049c16f/sync/sync.py#L25)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

> scripts in charge of data deletion should read from cloud
> datastore directly.

This is what I was trying to express to you on the balcony the other day. I disagree that clients should read from datastore directly. Is this the long term migration we want?
</blockquote></details>

Wording changed to reflect the idea that we aren't sure of the right architecture for the future, but we are sure that it's not the sheets api, or any other data source that is so regularly behind the times.

---

*[sync/sync.py, line 29 at r1](https://reviewable.io:443/reviews/m-lab/scraper/27#-KgWIvLnhPSmQ6fzOqf7:-KgZjAff59fFoUk2QphE:b-896fix) ([raw file](https://github.com/m-lab/scraper/blob/081a53afd2c75dbd7179b59e7c3ee69ee049c16f/sync/sync.py#L29)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

nit. missing period: "API  Sheets
</blockquote></details>

Done.

---

*[sync/sync.py, line 129 at r1](https://reviewable.io:443/reviews/m-lab/scraper/27#-KgWLRvFEl1tNvnMSJR1:-KgZZkt7OBpRetiP73cc:bv63gv) ([raw file](https://github.com/m-lab/scraper/blob/081a53afd2c75dbd7179b59e7c3ee69ee049c16f/sync/sync.py#L129)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

What do you think of adding the remote IP here, to give an extra hint in the logs, just in case?
</blockquote></details>

Done. This was accidentally left in, actually. But logging the request seems like a good idea.

---

*[sync/sync.py, line 153 at r1](https://reviewable.io:443/reviews/m-lab/scraper/27#-KgWO1tKmZ3LeN2R0Yey:-KgZrKzqQJaLSIfRy2tW:boj0wq) ([raw file](https://github.com/m-lab/scraper/blob/081a53afd2c75dbd7179b59e7c3ee69ee049c16f/sync/sync.py#L153)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

If something was funny with datastore, and the spreadsheet wasn't getting updated, and an operator came to visit this page to investigate, but `datastore_client.query` raised an exception (b/c datastore is funny) what would the operator see at this point?
</blockquote></details>

Added exception catching and stack trace printing.

---

*[sync/sync_test.py, line 75 at r1](https://reviewable.io:443/reviews/m-lab/scraper/27#-KgWQurFw23X-ZzC95Kk:-KgZZXPGZ1PIeeE3OCJH:bsb7ufp) ([raw file](https://github.com/m-lab/scraper/blob/081a53afd2c75dbd7179b59e7c3ee69ee049c16f/sync/sync_test.py#L75)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Optional: I really like the idea of testing whether a system has help text. How do we know if it worked vs the flag being unsupported?
</blockquote></details>

Dunno.

---

*[sync/sync_test.py, line 90 at r1](https://reviewable.io:443/reviews/m-lab/scraper/27#-KgWXysx8clRUeue-sXq:-KgZZMeeTHhkGPAQygrd:bdiqy1n) ([raw file](https://github.com/m-lab/scraper/blob/081a53afd2c75dbd7179b59e7c3ee69ee049c16f/sync/sync_test.py#L90)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Where possible, separate "arrange", "act" and "assert" blocks separated by white space helps improve the readability of unit tests, by visually contrasting each block. Here and below, I found myself searching for the method under test a little more. What do you think of separating these blocks here and in the `do_get` tests?
</blockquote></details>

Done. (for the tests with large setups, that is)

---

*[sync/sync_test.py, line 115 at r1](https://reviewable.io:443/reviews/m-lab/scraper/27#-KgWSc6uT9Cu1HiCZ5hm:-KgZZVF3Z-KI8yAInR3n:b-896fix) ([raw file](https://github.com/m-lab/scraper/blob/081a53afd2c75dbd7179b59e7c3ee69ee049c16f/sync/sync_test.py#L115)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

`assertItemsEqual`? I think there's a difference in how the diff is reported when an error occurs that makes `assertItemsEqual` preferable. Can you confirm?
</blockquote></details>

Done.

---

*[sync/sync_test.py, line 117 at r1](https://reviewable.io:443/reviews/m-lab/scraper/27#-KgWTNvBrzZ4X7Un43JD:-KgZTwnmlzFP132GV7hY:b-nntypa) ([raw file](https://github.com/m-lab/scraper/blob/081a53afd2c75dbd7179b59e7c3ee69ee049c16f/sync/sync_test.py#L117)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Since we're testing `do_GET` in this unit test, my bias would be toward mocking `get_fleet_data`. This strategy requires only shallow knowledge of the implementation, rather than two levels deep. This will be easier for `test_do_get_no_data` below. What do you think?
</blockquote></details>

There are two reasons I prefer my approach, one theoretical and one practical. 

The theoretical one is that all I should need to mock in these tests is the external services and python's libraries. In particular, the test for do _GET should not need to know how the method gets data from datastore, just that it does so, so by mocking the external service we reflect that.

The practical reason is that there's a lot of strings that need to be arranged just-so, and so using just the one fake in the `setUp` method saves a lot of clutter and extra lines. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/27)*

**Comment by stephen-soltesz** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[sync/sync.py, line 153 at r1](https://reviewable.io:443/reviews/m-lab/scraper/27#-KgWO1tKmZ3LeN2R0Yey:-KgZu1rLSCBYRoPJSinK:bigcomd) ([raw file](https://github.com/m-lab/scraper/blob/081a53afd2c75dbd7179b59e7c3ee69ee049c16f/sync/sync.py#L153)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Added exception catching and stack trace printing.
</blockquote></details>

Cool. Thank you.

---

*[sync/sync.py, line 156 at r2](https://reviewable.io:443/reviews/m-lab/scraper/27#-KgZu43IEiOwF68wzIPI:-KgZu43IEiOwF68wzIPJ:b-ia2bfu) ([raw file](https://github.com/m-lab/scraper/blob/850cfeb2cc3e12d5830d5c3dba12d2d624935557/sync/sync.py#L156)):*
> ```Python
>         try:
>             data = get_fleet_data(WebHandler.namespace)
> 	# This will be used for debugging errors, so catching an overly-broad
> ```

nit: tabs.

---

*[sync/sync_test.py, line 75 at r1](https://reviewable.io:443/reviews/m-lab/scraper/27#-KgWQurFw23X-ZzC95Kk:-KgZu92T01vL3wMzbozA:b-csepp0) ([raw file](https://github.com/m-lab/scraper/blob/081a53afd2c75dbd7179b59e7c3ee69ee049c16f/sync/sync_test.py#L75)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Dunno.
</blockquote></details>

From in person discussion, this is harder than it sounds, and '-h' is a distinct enough case from the other cases already tested to leave in.

---

*[sync/sync_test.py, line 90 at r1](https://reviewable.io:443/reviews/m-lab/scraper/27#-KgWXysx8clRUeue-sXq:-KgZudXm3bEu6NYdBEnP:bigcom0) ([raw file](https://github.com/m-lab/scraper/blob/081a53afd2c75dbd7179b59e7c3ee69ee049c16f/sync/sync_test.py#L90)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Done. (for the tests with large setups, that is)
</blockquote></details>

Cool. Thank you!

---

*[sync/sync_test.py, line 117 at r1](https://reviewable.io:443/reviews/m-lab/scraper/27#-KgWTNvBrzZ4X7Un43JD:-KgZuiQlOX-GWFvdmJGI:b6wt6kj) ([raw file](https://github.com/m-lab/scraper/blob/081a53afd2c75dbd7179b59e7c3ee69ee049c16f/sync/sync_test.py#L117)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

There are two reasons I prefer my approach, one theoretical and one practical. 

The theoretical one is that all I should need to mock in these tests is the external services and python's libraries. In particular, the test for do _GET should not need to know how the method gets data from datastore, just that it does so, so by mocking the external service we reflect that.

The practical reason is that there's a lot of strings that need to be arranged just-so, and so using just the one fake in the `setUp` method saves a lot of clutter and extra lines. 
</blockquote></details>

I recognized the practical reason when I wrote the original comment. I see your point about modeling the external service. I'll meditate on this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/27#-:-KgZuwhDk-2agWh3QQaW:bnfp4nl)*

**Comment by pboothe** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[sync/sync.py, line 156 at r2](https://reviewable.io:443/reviews/m-lab/scraper/27#-KgZu43IEiOwF68wzIPI:-Kg_4KXVeciLCcFX4d-o:bsiitjc) ([raw file](https://github.com/m-lab/scraper/blob/850cfeb2cc3e12d5830d5c3dba12d2d624935557/sync/sync.py#L156)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

nit: tabs.
</blockquote></details>

Fixed. [shamecube.gif]

---

*[sync/sync_test.py, line 117 at r1](https://reviewable.io:443/reviews/m-lab/scraper/27#-KgWTNvBrzZ4X7Un43JD:-Kg_4tgAjRiWAyFqXeJT:b32w1v) ([raw file](https://github.com/m-lab/scraper/blob/081a53afd2c75dbd7179b59e7c3ee69ee049c16f/sync/sync_test.py#L117)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I recognized the practical reason when I wrote the original comment. I see your point about modeling the external service. I'll meditate on this.
</blockquote></details>

Om

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/27)*

**Pull request merged**
