### PR TITLE
A working spreadsheet and test coverage thereof!

### PR DESCRIPTION
**Pull request by pboothe**
Sync the datastore data up to the spreadsheet.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/scraper/29)

### CODE REVIEW

**Comment by pboothe** [comment]
On the way to #28

**Comment by stephen-soltesz** [comment]
Reviewed 4 of 6 files at r1.
Review status: 4 of 6 files reviewed at latest revision, 12 unresolved discussions.

---

*[sync/sync.py, line 61 at r2](https://reviewable.io:443/reviews/m-lab/scraper/29#-Kh-4S-nVi8CXNfnxbX4:-Kh-4S-on3csPaCWOnsV:b-7uv9r2) ([raw file](https://github.com/m-lab/scraper/blob/8adb30526afd30f4dc41759e1cf2c4321c1f1faf/sync/sync.py#L61)):*
> ```Python
> # compromise between exponentially-sized bucket growth and a desire to make
> # sure that the bucket sizes are nice round time units.
> TIME_BUCKETS = (1.0, 2.0, 5.0, 10.0, 30.0, 60.0, 120.0, 300.0, 600.0,
> ```

Are the buckets inline with our expected distribution of times for sync times and sleep times?

---

*[sync/sync.py, line 243 at r2](https://reviewable.io:443/reviews/m-lab/scraper/29#-KgztnrtpLabr7Pbd8dv:-KgztnruRiW0msZtSiem:b-f204mg) ([raw file](https://github.com/m-lab/scraper/blob/8adb30526afd30f4dc41759e1cf2c4321c1f1faf/sync/sync.py#L243)):*
> ```Python
>         Used to ensure that the update process does not re-order rows.
>         """
>         sheet_range = self._worksheet + '!A:' + chr(ord('A') + len(KEYS))
> ```

A comment like this would have saved me a little time.

    # Sheet ranges have the form: <worksheet name>!<col1>:<col2>

---

*[sync/sync.py, line 251 at r2](https://reviewable.io:443/reviews/m-lab/scraper/29#-Kgzvecbqex5L6SrqgYo:-Kgzvecbqex5L6SrqgYp:bps3qb6) ([raw file](https://github.com/m-lab/scraper/blob/8adb30526afd30f4dc41759e1cf2c4321c1f1faf/sync/sync.py#L251)):*
> ```Python
>         else:
>             logging.warning('No data found on spreadsheet.')
>             return KEYS, []
> ```

Other than the first time a spreadsheet is used (and initially empty), would this case be possible? If so, it seems important, and I'm wondering if it would be worthwhile counting in `SUCCESS.labels`? This also may not matter if we can count on the syncer to just fix things on subsequent runs. My thought is that there's a mismatch between the `warning` log and how often this is expected and whether we count it.

---

*[sync/sync.py, line 255 at r2](https://reviewable.io:443/reviews/m-lab/scraper/29#-KgzuyTW2Jhww5ESAdjH:-KgzuyTXfhqdG1kz2-yS:byg15qx) ([raw file](https://github.com/m-lab/scraper/blob/8adb30526afd30f4dc41759e1cf2c4321c1f1faf/sync/sync.py#L255)):*
> ```Python
>     def _update_spreadsheet(self, header, rows):
>         """Sets the contents of the spreadsheet."""
>         update_range = (self._worksheet +
> ```

This sheet range is a different form from the query range above, and the expression takes three lines to compose. Would you be willing to add a comparable one-line comment to summarize what is being generated?

---

*[sync/sync.py, line 257 at r2](https://reviewable.io:443/reviews/m-lab/scraper/29#-KgzvSvlaxI8AnnoFB5h:-KgzvSvlaxI8AnnoFB5i:b-gwbpvt) ([raw file](https://github.com/m-lab/scraper/blob/8adb30526afd30f4dc41759e1cf2c4321c1f1faf/sync/sync.py#L257)):*
> ```Python
>         update_range = (self._worksheet +
>                         '!A1:' + chr(ord('A') + len(header))
>                         + str(len(rows) + 2))
> ```

Why `+2`? I'm sure there's a good reason, it's just not apparent to me.

---

*[sync/sync.py, line 264 at r2](https://reviewable.io:443/reviews/m-lab/scraper/29#-Kgzvc2z9IWdknP9pszA:-Kgzvc2z9IWdknP9pszB:b-p9p1ja) ([raw file](https://github.com/m-lab/scraper/blob/8adb30526afd30f4dc41759e1cf2c4321c1f1faf/sync/sync.py#L264)):*
> ```Python
>             body=body, valueInputOption='RAW').execute()
>         if not response['updatedRows']:
>             logging.error('Spreadsheet update failed (%s)', response)
> ```

Is this possible? If so, would it be worthwhile counting it in `SUCCESS.labels`?

---

*[sync/sync.py, line 310 at r2](https://reviewable.io:443/reviews/m-lab/scraper/29#-Kgzxt5NK_IXYiWl6Jwp:-Kgzxt5NK_IXYiWl6Jwq:b8cfa33) ([raw file](https://github.com/m-lab/scraper/blob/8adb30526afd30f4dc41759e1cf2c4321c1f1faf/sync/sync.py#L310)):*
> ```Python
>     # Set up spreadsheet client
>     creds = gce.AppAssertionCredentials()
>     discovery_url = ('https://sheets.googleapis.com/$discovery/rest?'
> ```

General question: is it true that if one pod within a k8s cluster needs a specific scope (e.g. spreadsheets), then the entire cluster (and any pod in the cluster) could also get credentials with that scope?

---

*[sync/sync.py, line 333 at r2](https://reviewable.io:443/reviews/m-lab/scraper/29#-KgzzgF2K2SEsC0hnD8F:-KgzzgF2K2SEsC0hnD8G:b-twxz64) ([raw file](https://github.com/m-lab/scraper/blob/8adb30526afd30f4dc41759e1cf2c4321c1f1faf/sync/sync.py#L333)):*
> ```Python
>         sleep_time = random.expovariate(1.0 / args.expected_upload_interval)
>         logging.info('Sleeping for %g seconds', sleep_time)
>         with SLEEPS.time():
> ```

There's only one syncer right?

Do we need to stagger the update times?

---

*[sync/sync_test.py, line 175 at r2](https://reviewable.io:443/reviews/m-lab/scraper/29#-Kh--vwuZiQ_HxYQC6lS:-Kh--vwvS_Mt_Zdxn3Yj:bcxa6qw) ([raw file](https://github.com/m-lab/scraper/blob/8adb30526afd30f4dc41759e1cf2c4321c1f1faf/sync/sync_test.py#L175)):*
> ```Python
>             'updatedRows': 'a value'
>         }
>         sheet = sync.Spreadsheet(mock_service, 'test_id')
> ```

Would you be willing to separate the arrange, act, and assert blocks in these tests as well?

---

*[sync/sync_test.py, line 177 at r2](https://reviewable.io:443/reviews/m-lab/scraper/29#-Kh-08AsKG29e64gKeWz:-Kh-08AsKG29e64gKeX-:bsedp3n) ([raw file](https://github.com/m-lab/scraper/blob/8adb30526afd30f4dc41759e1cf2c4321c1f1faf/sync/sync_test.py#L177)):*
> ```Python
>         sheet = sync.Spreadsheet(mock_service, 'test_id')
>         sheet.update(sync.get_fleet_data('test_namespace'))
>         self.assertIn('WARNING', [x.levelname for x in log.records])
> ```

Is there any more direct way we can verify to confirm the `update` was successful other than the logs?

For example, can we confirm that `self._service.spreadsheets().values().update().execute()` was called?

---

*[sync/sync_test.py, line 195 at r2](https://reviewable.io:443/reviews/m-lab/scraper/29#-Kh-11n9U2_NKM7J-7m3:-Kh-11nAlwGijibLQd9N:bius5og) ([raw file](https://github.com/m-lab/scraper/blob/8adb30526afd30f4dc41759e1cf2c4321c1f1faf/sync/sync_test.py#L195)):*
> ```Python
>         }
>         sheet = sync.Spreadsheet(mock_service, 'test_id')
>         sheet.update(sync.get_fleet_data('test_namespace'))
> ```

Please assert something. In this case, my thought is to verify that the result correctly merges the datastore data (3 records) with the current spreadsheet data (1 record) such that the result is still only 3 records (rather than accidentally appending the three new ones). This is one of the constraints that the `update` promises to provide.

---

*[sync/sync_test.py, line 214 at r2](https://reviewable.io:443/reviews/m-lab/scraper/29#-Kh-1k_DXodgljFYfEk8:-Kh-1k_DXodgljFYfEk9:b-jk68ba) ([raw file](https://github.com/m-lab/scraper/blob/8adb30526afd30f4dc41759e1cf2c4321c1f1faf/sync/sync_test.py#L214)):*
> ```Python
>         sheet = sync.Spreadsheet(mock_service, 'test_id')
>         sheet.update(sync.get_fleet_data('test_namespace'))
>         self.assertIn('ERROR', [x.levelname for x in log.records])
> ```

If the update fails repeatedly without an exception (which the code implies could happen), we want to be able to detect this in monitoring. Can this fail repeatedly?

Like the earlier tests, please confirm that the `update` call is made.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/29)*

**Comment by pboothe** [comment]
Review status: 4 of 6 files reviewed at latest revision, 12 unresolved discussions.

---

*[sync/sync.py, line 61 at r2](https://reviewable.io:443/reviews/m-lab/scraper/29#-Kh-4S-nVi8CXNfnxbX4:-Kh-8WHg0GN0C2sC7tHa:bvprypm) ([raw file](https://github.com/m-lab/scraper/blob/8adb30526afd30f4dc41759e1cf2c4321c1f1faf/sync/sync.py#L61)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Are the buckets inline with our expected distribution of times for sync times and sleep times?
</blockquote></details>

Sleep times yes. Sync times... I think so? If this is not true in practice, I will change the buckets for RUNS.

---

*[sync/sync.py, line 243 at r2](https://reviewable.io:443/reviews/m-lab/scraper/29#-KgztnrtpLabr7Pbd8dv:-Kh-9EtEy88DwM8MDqWa:b-896fix) ([raw file](https://github.com/m-lab/scraper/blob/8adb30526afd30f4dc41759e1cf2c4321c1f1faf/sync/sync.py#L243)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

A comment like this would have saved me a little time.

    # Sheet ranges have the form: <worksheet name>!<col1>:<col2>
</blockquote></details>

Done.

---

*[sync/sync.py, line 251 at r2](https://reviewable.io:443/reviews/m-lab/scraper/29#-Kgzvecbqex5L6SrqgYo:-Kh2usXuGCYHQ92mVeS7:b-iavdab) ([raw file](https://github.com/m-lab/scraper/blob/8adb30526afd30f4dc41759e1cf2c4321c1f1faf/sync/sync.py#L251)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Other than the first time a spreadsheet is used (and initially empty), would this case be possible? If so, it seems important, and I'm wondering if it would be worthwhile counting in `SUCCESS.labels`? This also may not matter if we can count on the syncer to just fix things on subsequent runs. My thought is that there's a mismatch between the `warning` log and how often this is expected and whether we count it.
</blockquote></details>

This made no distinction between the successful retrieval of an empty sheet (expected) and a failure to retrieve anything at all (should not happen). The first case is a log message, the second is now an exception.

---

*[sync/sync.py, line 255 at r2](https://reviewable.io:443/reviews/m-lab/scraper/29#-KgzuyTW2Jhww5ESAdjH:-Kh-9GfVnxj_KompNDyk:b-896fix) ([raw file](https://github.com/m-lab/scraper/blob/8adb30526afd30f4dc41759e1cf2c4321c1f1faf/sync/sync.py#L255)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

This sheet range is a different form from the query range above, and the expression takes three lines to compose. Would you be willing to add a comparable one-line comment to summarize what is being generated?
</blockquote></details>

Done.

---

*[sync/sync.py, line 257 at r2](https://reviewable.io:443/reviews/m-lab/scraper/29#-KgzvSvlaxI8AnnoFB5h:-Kh-9HoKyvZ9o8GkMokX:b-ks84vs) ([raw file](https://github.com/m-lab/scraper/blob/8adb30526afd30f4dc41759e1cf2c4321c1f1faf/sync/sync.py#L257)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Why `+2`? I'm sure there's a good reason, it's just not apparent to me.
</blockquote></details>

Added explanation. Realized it should be +1 in the process.

---

*[sync/sync.py, line 264 at r2](https://reviewable.io:443/reviews/m-lab/scraper/29#-Kgzvc2z9IWdknP9pszA:-Kh-6kJ_dBcHesCrZAze:b-ket4al) ([raw file](https://github.com/m-lab/scraper/blob/8adb30526afd30f4dc41759e1cf2c4321c1f1faf/sync/sync.py#L264)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Is this possible? If so, would it be worthwhile counting it in `SUCCESS.labels`?
</blockquote></details>

Whenever the sheets api has an error. You are right that I should make this throw an exception though. It is an exceptional circumstance.

---

*[sync/sync.py, line 310 at r2](https://reviewable.io:443/reviews/m-lab/scraper/29#-Kgzxt5NK_IXYiWl6Jwp:-Kh-6vRuD2j63qiwG7L6:b-x0paxg) ([raw file](https://github.com/m-lab/scraper/blob/8adb30526afd30f4dc41759e1cf2c4321c1f1faf/sync/sync.py#L310)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

General question: is it true that if one pod within a k8s cluster needs a specific scope (e.g. spreadsheets), then the entire cluster (and any pod in the cluster) could also get credentials with that scope?
</blockquote></details>

Yes :(

---

*[sync/sync.py, line 333 at r2](https://reviewable.io:443/reviews/m-lab/scraper/29#-KgzzgF2K2SEsC0hnD8F:-Kh-8FYZrkapJ6I4E7E3:b-mer394) ([raw file](https://github.com/m-lab/scraper/blob/8adb30526afd30f4dc41759e1cf2c4321c1f1faf/sync/sync.py#L333)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

There's only one syncer right?

Do we need to stagger the update times?
</blockquote></details>

In a distributed system, always add a little randomness unless you have a reason not to.

---

*[sync/sync_test.py, line 175 at r2](https://reviewable.io:443/reviews/m-lab/scraper/29#-Kh--vwuZiQ_HxYQC6lS:-Kh2sotNjdKgG2eiEAYw:b-896fix) ([raw file](https://github.com/m-lab/scraper/blob/8adb30526afd30f4dc41759e1cf2c4321c1f1faf/sync/sync_test.py#L175)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Would you be willing to separate the arrange, act, and assert blocks in these tests as well?
</blockquote></details>

Done.

---

*[sync/sync_test.py, line 177 at r2](https://reviewable.io:443/reviews/m-lab/scraper/29#-Kh-08AsKG29e64gKeWz:-Kh2sq2mlEqLHB0COIwL:b-896fix) ([raw file](https://github.com/m-lab/scraper/blob/8adb30526afd30f4dc41759e1cf2c4321c1f1faf/sync/sync_test.py#L177)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Is there any more direct way we can verify to confirm the `update` was successful other than the logs?

For example, can we confirm that `self._service.spreadsheets().values().update().execute()` was called?
</blockquote></details>

Done.

---

*[sync/sync_test.py, line 195 at r2](https://reviewable.io:443/reviews/m-lab/scraper/29#-Kh-11n9U2_NKM7J-7m3:-Kh2rLm8mi3sORMoyJLy:b-896fix) ([raw file](https://github.com/m-lab/scraper/blob/8adb30526afd30f4dc41759e1cf2c4321c1f1faf/sync/sync_test.py#L195)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please assert something. In this case, my thought is to verify that the result correctly merges the datastore data (3 records) with the current spreadsheet data (1 record) such that the result is still only 3 records (rather than accidentally appending the three new ones). This is one of the constraints that the `update` promises to provide.
</blockquote></details>

Done.

---

*[sync/sync_test.py, line 214 at r2](https://reviewable.io:443/reviews/m-lab/scraper/29#-Kh-1k_DXodgljFYfEk8:-Kh2snnXncYZZQ4NTq9i:b-896fix) ([raw file](https://github.com/m-lab/scraper/blob/8adb30526afd30f4dc41759e1cf2c4321c1f1faf/sync/sync_test.py#L214)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

If the update fails repeatedly without an exception (which the code implies could happen), we want to be able to detect this in monitoring. Can this fail repeatedly?

Like the earlier tests, please confirm that the `update` call is made.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/29)*

**Comment by stephen-soltesz** [comment]
Thank you for the updates. The tests look great.

A few small requests remaining in `sync.py`.

---

Reviewed 1 of 2 files at r3.
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[sync/sync.py, line 61 at r2](https://reviewable.io:443/reviews/m-lab/scraper/29#-Kh-4S-nVi8CXNfnxbX4:-Kh469Jd8W1X8a0NRaT2:b-99rdxc) ([raw file](https://github.com/m-lab/scraper/blob/8adb30526afd30f4dc41759e1cf2c4321c1f1faf/sync/sync.py#L61)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Sleep times yes. Sync times... I think so? If this is not true in practice, I will change the buckets for RUNS.
</blockquote></details>

Ah, okay. I was misunderstanding how `random.expovariate(1.0 / args.expected_upload_interval)` works and what sleep times were possible.

In this case, the previous expectation around the spreadsheet was that it would be updated at least once an hour. These sleep times can be longer than an hour (though increasingly less likely). Can we preserve a minimum update period of once per hour? I don't want to change the intuition for something that the nodes depend on.

---

*[sync/sync.py, line 255 at r2](https://reviewable.io:443/reviews/m-lab/scraper/29#-KgzuyTW2Jhww5ESAdjH:-Kh42i1_13zlO-NXZS6F:bvw8j8x) ([raw file](https://github.com/m-lab/scraper/blob/8adb30526afd30f4dc41759e1cf2c4321c1f1faf/sync/sync.py#L255)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

My thought was that:
```
<worksheet name>!<col1>:<col2>
```

is different from:
```
<worksheet name>!<col1><row1>:<col2><row2>
```
Where in the second form, there are also rows. Please add rows to this comment.

Thank you for taking the time to look at this. I believe it will help anyone who needs to interpret the code in the future.

---

*[sync/sync.py, line 257 at r2](https://reviewable.io:443/reviews/m-lab/scraper/29#-KgzvSvlaxI8AnnoFB5h:-Kh43DVeTZ1McNrw3cmY:bb6mt9b) ([raw file](https://github.com/m-lab/scraper/blob/8adb30526afd30f4dc41759e1cf2c4321c1f1faf/sync/sync.py#L257)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Added explanation. Realized it should be +1 in the process.
</blockquote></details>

:+1:

---

*[sync/sync.py, line 310 at r2](https://reviewable.io:443/reviews/m-lab/scraper/29#-Kgzxt5NK_IXYiWl6Jwp:-Kh43UBT2qg0z_Nm8nX8:b-y8omag) ([raw file](https://github.com/m-lab/scraper/blob/8adb30526afd30f4dc41759e1cf2c4321c1f1faf/sync/sync.py#L310)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Yes :(
</blockquote></details>

Okay. Interesting. This is may be another checkbox in the "why we want multiple clusters" list.

---

*[sync/sync.py, line 361 at r3](https://reviewable.io:443/reviews/m-lab/scraper/29#-Kh44KCOYPDDUhjWifN7:-Kh44KCOYPDDUhjWifN8:bgs40gz) ([raw file](https://github.com/m-lab/scraper/blob/efbc7db6a203546d7da36f48e943bf67545f01e6/sync/sync.py#L361)):*
> ```Python
>             SUCCESS.labels(message='success').inc()
>         except (SyncException, Exception) as error:
>             SUCCESS.labels(message=str(error.message)).inc()
> ```

Looking at the code, now I'm worried that the exception message could get pretty hairy and that the content of those messages will not be suitable for ingestion by prometheus. Please use the exception type name instead. If something is happening frequently enough to investigate, an operator will be able to find the specific messages in the logs.

---

*[sync/sync_test.py, line 214 at r2](https://reviewable.io:443/reviews/m-lab/scraper/29#-Kh-1k_DXodgljFYfEk8:-Kh4ANQmvKUrw17Auiqi:b47ksbo) ([raw file](https://github.com/m-lab/scraper/blob/8adb30526afd30f4dc41759e1cf2c4321c1f1faf/sync/sync_test.py#L214)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks, these all look great.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/29#-:-Kh4AtQYaEvQnD1feuz7:b-6w0ntz)*

**Comment by pboothe** [comment]
Review status: 5 of 6 files reviewed at latest revision, 6 unresolved discussions.

---

*[sync/sync.py, line 61 at r2](https://reviewable.io:443/reviews/m-lab/scraper/29#-Kh-4S-nVi8CXNfnxbX4:-Kh7lmWs6CIJR5CYTPh9:builm0m) ([raw file](https://github.com/m-lab/scraper/blob/8adb30526afd30f4dc41759e1cf2c4321c1f1faf/sync/sync.py#L61)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Ah, okay. I was misunderstanding how `random.expovariate(1.0 / args.expected_upload_interval)` works and what sleep times were possible.

In this case, the previous expectation around the spreadsheet was that it would be updated at least once an hour. These sleep times can be longer than an hour (though increasingly less likely). Can we preserve a minimum update period of once per hour? I don't want to change the intuition for something that the nodes depend on.
</blockquote></details>

Sure. It kind of feels like adding a hack to prevent something that is both harmless and exponentially unlikely, but I understand where the worry is coming from.  Ceiling has been added.

---

*[sync/sync.py, line 255 at r2](https://reviewable.io:443/reviews/m-lab/scraper/29#-KgzuyTW2Jhww5ESAdjH:-Kh7mBoMb0C8yOI2-SYX:b-896fix) ([raw file](https://github.com/m-lab/scraper/blob/8adb30526afd30f4dc41759e1cf2c4321c1f1faf/sync/sync.py#L255)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

My thought was that:
```
<worksheet name>!<col1>:<col2>
```

is different from:
```
<worksheet name>!<col1><row1>:<col2><row2>
```
Where in the second form, there are also rows. Please add rows to this comment.

Thank you for taking the time to look at this. I believe it will help anyone who needs to interpret the code in the future.
</blockquote></details>

Done.

---

*[sync/sync.py, line 361 at r3](https://reviewable.io:443/reviews/m-lab/scraper/29#-Kh44KCOYPDDUhjWifN7:-Kh7kwJfnA268DGEVTXg:b-896fix) ([raw file](https://github.com/m-lab/scraper/blob/efbc7db6a203546d7da36f48e943bf67545f01e6/sync/sync.py#L361)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Looking at the code, now I'm worried that the exception message could get pretty hairy and that the content of those messages will not be suitable for ingestion by prometheus. Please use the exception type name instead. If something is happening frequently enough to investigate, an operator will be able to find the specific messages in the logs.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/29)*

**Comment by stephen-soltesz** [comment]
One typo.

:lgtm:

---

Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[sync/sync.py, line 275 at r4](https://reviewable.io:443/reviews/m-lab/scraper/29#-Kh7rESkjuas12o121DM:-Kh7rESkjuas12o121DN:b-gualz0) ([raw file](https://github.com/m-lab/scraper/blob/8e0ea5d4495772d20f322b9e934735f05aae9bd4/sync/sync.py#L275)):*
> ```Python
>         """
>         # Sheet ranges have the form: <worksheet name>!<col1><row1>:<col2><row2>
> 	# Column names are alphabetical starting with 'A'.  The code below will
> ```

MORE TABS!!!!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/29#-:-Kh7rSX6F3FDhxENOohR:bidea2f)*

**Comment by pboothe** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[sync/sync.py, line 275 at r4](https://reviewable.io:443/reviews/m-lab/scraper/29#-Kh7rESkjuas12o121DM:-Kh8_OAuiMkIiG-YPfmt:b-896fix) ([raw file](https://github.com/m-lab/scraper/blob/8e0ea5d4495772d20f322b9e934735f05aae9bd4/sync/sync.py#L275)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

MORE TABS!!!!
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/29)*

**Pull request merged**
