### PR TITLE
Export file counts for every successfully uploaded day.

### PR DESCRIPTION
**Pull request by pboothe**
This should allow us to check, after parsing, whether the number of files scraper thinks it saved is the same as the number of files the parser found and parsed.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/scraper/68)

### CODE REVIEW

**Comment by pboothe** [comment]
Coveralls had a little hiccup when posting the comment, but if you look under "show all checks" you will see that coverage remains at 100%

**Comment by gfr10598** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[scraper.py, line 77 at r1](https://reviewable.io:443/reviews/m-lab/scraper/68#-KmhReCh7N77exTdTOwd:-KmhReCh7N77exTdTOwe:b-u1kdtg) ([raw file](https://github.com/m-lab/scraper/blob/1b929d0af06eaaefd1687fe021799c1d304d59cb/scraper.py#L77)):*
> ```Python
>     'Total bytes uploaded to GCS',
>     ['bucket'])
> FILES_UPLOADED = prometheus_client.Gauge(
> ```

I think this should still be a counter.  Prometheus query can use e.g., increment[6d] to get change for a particular interval.

---

*[scraper.py, line 79 at r1](https://reviewable.io:443/reviews/m-lab/scraper/68#-KmhRwR6zLggdf_b1ESb:-KmhRwR6zLggdf_b1ESc:b-duilp4) ([raw file](https://github.com/m-lab/scraper/blob/1b929d0af06eaaefd1687fe021799c1d304d59cb/scraper.py#L79)):*
> ```Python
> FILES_UPLOADED = prometheus_client.Gauge(
>     'scraper_files_uploaded',
>     'Total file count of the files uploaded to GCS over the last 7 days',
> ```

'Total file count of test files uploaded to GCS'

test - to distinguish from tar files, and make the counting dead simple.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/68)*

**Comment by pboothe** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[scraper.py, line 77 at r1](https://reviewable.io:443/reviews/m-lab/scraper/68#-KmhReCh7N77exTdTOwd:-KmhVyxPyWg5GELrlSIE:bb6un1j) ([raw file](https://github.com/m-lab/scraper/blob/1b929d0af06eaaefd1687fe021799c1d304d59cb/scraper.py#L77)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

I think this should still be a counter.  Prometheus query can use e.g., increment[6d] to get change for a particular interval.
</blockquote></details>

Done

---

*[scraper.py, line 79 at r1](https://reviewable.io:443/reviews/m-lab/scraper/68#-KmhRwR6zLggdf_b1ESb:-KmhVzqPRZn5bKFxxYL1:bb6un1j) ([raw file](https://github.com/m-lab/scraper/blob/1b929d0af06eaaefd1687fe021799c1d304d59cb/scraper.py#L79)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

'Total file count of test files uploaded to GCS'

test - to distinguish from tar files, and make the counting dead simple.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/68)*

**Comment by gfr10598** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[operator, line 1 at r2](https://reviewable.io:443/reviews/m-lab/scraper/68#-KmhXAXyf-0aD6DwuAFb:-KmhXAXyf-0aD6DwuAFc:b-eg6riq) ([raw file](https://github.com/m-lab/scraper/blob/5882d9d02713a775402681ab609783a369b6a918/operator#L1)):*
> ```
> Subproject commit 5dc1ba8c434658184f345816227b7b332e045ca9
> ```

Why is this being updated?

---

*[scraper.py, line 943 at r2](https://reviewable.io:443/reviews/m-lab/scraper/68#-KmhWnPzgffw4HUEQnA3:-KmhWnQ-j7NmUyjjohk7:b1l4gzq) ([raw file](https://github.com/m-lab/scraper/blob/5882d9d02713a775402681ab609783a369b6a918/scraper.py#L943)):*
> ```Python
>             BYTES_UPLOADED.labels(bucket=args.bucket).inc(
>                 os.stat(tgz_filename).st_size)
>         FILES_UPLOADED.labels(
> ```

Please comment why you do it here instead of in the loop.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/68#-:-KmhX7SmS0DP8szD287k:bnfp4nl)*

**Comment by pboothe** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[operator, line 1 at r2](https://reviewable.io:443/reviews/m-lab/scraper/68#-KmhXAXyf-0aD6DwuAFb:-KmlAD1FTM-UJm_k6olc:bx6aujr) ([raw file](https://github.com/m-lab/scraper/blob/5882d9d02713a775402681ab609783a369b6a918/operator#L1)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Why is this being updated?
</blockquote></details>

New sites means scraper needs the latest version of the operator repo. It was an unintentional inclusion, but it does need to be updated.

---

*[scraper.py, line 943 at r2](https://reviewable.io:443/reviews/m-lab/scraper/68#-KmhWnPzgffw4HUEQnA3:-KmlA9O5dVexul4UCTYc:b-896fix) ([raw file](https://github.com/m-lab/scraper/blob/5882d9d02713a775402681ab609783a369b6a918/scraper.py#L943)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Please comment why you do it here instead of in the loop.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/68)*

**Pull request merged**
