### PR TITLE
A bash script to verify that we have the same data for June from both systems

### PR DESCRIPTION
**Pull request by pboothe**
It is robust to subfiles being compressed in the new repo but not in the existing one.

The successful running of this script will help solve issue #107

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/scraper/106)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[validation/verify-old-vs-new-june2017.sh, line 5 at r1](https://reviewable.io:443/reviews/m-lab/scraper/106#-Kq8tf9xmoyvie2M4iQf:-Kq8tf9xmoyvie2M4iQg:b-da85kg) ([raw file](https://github.com/m-lab/scraper/blob/0fa51d0f1ffba48a8aae9596a73f0dea2507a46f/validation/verify-old-vs-new-june2017.sh#L5)):*
> ```Shell
> # A one-shot script that verifies that the data contained in the gs://mlab
> # bucket is a subset of the data contained in the gs://archive-mlab-oti for the
> # ndt/2017/06/ in each bucket.
> ```

I recommend also reviewing data from the core services "sidestream", "paris traceroute" and disco's "switch" data.

---

*[validation/verify-old-vs-new-june2017.sh, line 28 at r1](https://reviewable.io:443/reviews/m-lab/scraper/106#-Kq8v3mWLVaG1FI-2epf:-Kq8v3mWLVaG1FI-2epg:b-inb0a3) ([raw file](https://github.com/m-lab/scraper/blob/0fa51d0f1ffba48a8aae9596a73f0dea2507a46f/validation/verify-old-vs-new-june2017.sh#L28)):*
> ```Shell
>   if [[ -f ${oldfile} && -f ${newfile} ]]
>   then
>     if ! zdiff -q ${oldfile} ${newfile}
> ```

We need the logic built into `zdiff` b/c oldfile may be uncompressed while newfile may be compressed?

Are there ever cases of uncompressed & compressed versions being in the legacy archives?

---

*[validation/verify-old-vs-new-june2017.sh, line 47 at r1](https://reviewable.io:443/reviews/m-lab/scraper/106#-Kq8wI3BXpOvtTNlCmri:-Kq8wI3CdzUvcfkHIFre:b-gkl7ib) ([raw file](https://github.com/m-lab/scraper/blob/0fa51d0f1ffba48a8aae9596a73f0dea2507a46f/validation/verify-old-vs-new-june2017.sh#L47)):*
> ```Shell
>       for tgz in *.tgz
>       do
>         echo $tgz
> ```

I'm imagining this log line being hard to distinguish between the log line for new.

If this is difficult in practice, please prefix this log message with something indicating it's from the "old" bucket, and the one below with something indicating it's from the "new" bucket.

---

*[validation/verify-old-vs-new-june2017.sh, line 63 at r1](https://reviewable.io:443/reviews/m-lab/scraper/106#-Kq8y4s3kID0tduCOH41:-Kq8y4s3kID0tduCOH42:b6g3pis) ([raw file](https://github.com/m-lab/scraper/blob/0fa51d0f1ffba48a8aae9596a73f0dea2507a46f/validation/verify-old-vs-new-june2017.sh#L63)):*
> ```Shell
>       done
>     popd
>     # Only print out files that are in the legacy but not the new one.  These
> ```

This does only seems to count the missing files. Would it be helpful to list them?

---

*[validation/verify-old-vs-new-june2017.sh, line 76 at r1](https://reviewable.io:443/reviews/m-lab/scraper/106#-Kq8yMa1jqCry8TTdxAG:-Kq8yMa1jqCry8TTdxAH:bdtjzyy) ([raw file](https://github.com/m-lab/scraper/blob/0fa51d0f1ffba48a8aae9596a73f0dea2507a46f/validation/verify-old-vs-new-june2017.sh#L76)):*
> ```Shell
>     comm -1 -2 ${old}/filelist.txt <(cat ${new}/filelist.txt | sed -e 's/.gz$//' | sort -u) \
>       | grep -v filelist.txt | while read; do gzdiff $old $new ${REPLY}; done
>     echo "checked that all files ahave the same contents"
> ```

nit: typo - ahave.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/106)*

**Comment by pboothe** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[validation/verify-old-vs-new-june2017.sh, line 5 at r1](https://reviewable.io:443/reviews/m-lab/scraper/106#-Kq8tf9xmoyvie2M4iQf:-Kq907TYOVlHbyUOSFb-:b-kf3suo) ([raw file](https://github.com/m-lab/scraper/blob/0fa51d0f1ffba48a8aae9596a73f0dea2507a46f/validation/verify-old-vs-new-june2017.sh#L5)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I recommend also reviewing data from the core services "sidestream", "paris traceroute" and disco's "switch" data.
</blockquote></details>

Made it a command line parameter. Will run on parallel GCE instances.

---

*[validation/verify-old-vs-new-june2017.sh, line 28 at r1](https://reviewable.io:443/reviews/m-lab/scraper/106#-Kq8v3mWLVaG1FI-2epf:-Kq9-iyBixO5o9jJCGP5:b-a4qr48) ([raw file](https://github.com/m-lab/scraper/blob/0fa51d0f1ffba48a8aae9596a73f0dea2507a46f/validation/verify-old-vs-new-june2017.sh#L28)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

We need the logic built into `zdiff` b/c oldfile may be uncompressed while newfile may be compressed?

Are there ever cases of uncompressed & compressed versions being in the legacy archives?
</blockquote></details>

Not for NDT. But for belt&suspenders coverage I have added it to the script, because I am not as sure about the other experiments.

---

*[validation/verify-old-vs-new-june2017.sh, line 47 at r1](https://reviewable.io:443/reviews/m-lab/scraper/106#-Kq8wI3BXpOvtTNlCmri:-Kq90KGLwORVekEYucrV:b-xne2th) ([raw file](https://github.com/m-lab/scraper/blob/0fa51d0f1ffba48a8aae9596a73f0dea2507a46f/validation/verify-old-vs-new-june2017.sh#L47)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I'm imagining this log line being hard to distinguish between the log line for new.

If this is difficult in practice, please prefix this log message with something indicating it's from the "old" bucket, and the one below with something indicating it's from the "new" bucket.
</blockquote></details>

Removed the log lines. They weren't useful.

---

*[validation/verify-old-vs-new-june2017.sh, line 63 at r1](https://reviewable.io:443/reviews/m-lab/scraper/106#-Kq8y4s3kID0tduCOH41:-Kq90MDMST0G_z4WC0YN:b1ics3t) ([raw file](https://github.com/m-lab/scraper/blob/0fa51d0f1ffba48a8aae9596a73f0dea2507a46f/validation/verify-old-vs-new-june2017.sh#L63)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

This does only seems to count the missing files. Would it be helpful to list them?
</blockquote></details>

The hope is there are never any :). Added in the hopefully-never-executed enumeration

---

*[validation/verify-old-vs-new-june2017.sh, line 76 at r1](https://reviewable.io:443/reviews/m-lab/scraper/106#-Kq8yMa1jqCry8TTdxAG:-Kq90PwU37JZ9awdJhqq:bt2vr1b) ([raw file](https://github.com/m-lab/scraper/blob/0fa51d0f1ffba48a8aae9596a73f0dea2507a46f/validation/verify-old-vs-new-june2017.sh#L76)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

nit: typo - ahave.
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/106)*

**Comment by pboothe** [comment]
PTAL

---

Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/106#-:-Kq9IgXD1D7zZMmJmj4g:bb71pro)*

**Comment by stephen-soltesz** [comment]
:lgtm: :+1:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/106#-:-Kq9Kh1bXqkNfYts1jJb:bb67zex)*

**Comment by pboothe** [comment]
Undo LGTM, PTAL

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/106#-:-Kq9PME0iRrFdawTOKX4:bmg56fi)*

**Comment by stephen-soltesz** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[validation/verify-old-vs-new-june2017.sh, line 39 at r2](https://reviewable.io:443/reviews/m-lab/scraper/106#-Kq9RJKWfsDdMf38Axgi:-Kq9RJKWfsDdMf38Axgj:b-jc3a9u) ([raw file](https://github.com/m-lab/scraper/blob/652eba47e79d720edf2eca323b97f19474957b16/validation/verify-old-vs-new-june2017.sh#L39)):*
> ```Shell
>     if [[ ${experiment} == "sidestream" ]]
>     then
>       lines=$(comm -2 -3 <(sort ${oldfile})  <(sort ${newfile}) | wc -l)
> ```

newfile and oldfile could be compressed according to the logic. But, is that ever a possibility for sidestream logs?

---

*[validation/verify-old-vs-new-june2017.sh, line 43 at r2](https://reviewable.io:443/reviews/m-lab/scraper/106#-Kq9RaxWvq_AyaMY3rvQ:-Kq9RaxWvq_AyaMY3rvR:b-v8y2o2) ([raw file](https://github.com/m-lab/scraper/blob/652eba47e79d720edf2eca323b97f19474957b16/validation/verify-old-vs-new-june2017.sh#L43)):*
> ```Shell
>       then
>         echo FILES DIFFER: ${filename}
>         exit 1
> ```

do we want to exit rather than continue?

---

*[validation/verify-old-vs-new-june2017.sh, line 72 at r2](https://reviewable.io:443/reviews/m-lab/scraper/106#-Kq9QgtlYOobLhJ4EJ9w:-Kq9QgtlYOobLhJ4EJ9x:bz9sv9n) ([raw file](https://github.com/m-lab/scraper/blob/652eba47e79d720edf2eca323b97f19474957b16/validation/verify-old-vs-new-june2017.sh#L72)):*
> ```Shell
>     popd
>     pushd $new
>       gsutil -m cp gs://archive-mlab-oti/${EXPERIMENT}/2017/06/${day}/*${sliver}*.tgz . || gsutil -m cp gs://scraper-mlab-oti/${EXPERIMENT}/2017/06/${day}/*${sliver}*.tgz .
> ```

Please add a "\" to wrap this line before the `||`.

Please add a comment about why this is necessary (and when it might not be necessary any more).

---

*[validation/verify-old-vs-new-june2017.sh, line 88 at r2](https://reviewable.io:443/reviews/m-lab/scraper/106#-Kq9Rs_mjCUbg47ZtQ5Z:-Kq9Rs_n65lrKyVCQohN:b37jo4u) ([raw file](https://github.com/m-lab/scraper/blob/652eba47e79d720edf2eca323b97f19474957b16/validation/verify-old-vs-new-june2017.sh#L88)):*
> ```Shell
>     else
>       echo FILES MISSING FOR $day $sliver
>       comm -2 -3 ${old}/filelist.txt <(cat ${new}/filelist.txt | sed -e 's/.gz$//' | sort -u)
> ```

Does the old/filelist.txt also need to be sorted?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/106)*

**Comment by pboothe** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[validation/verify-old-vs-new-june2017.sh, line 39 at r2](https://reviewable.io:443/reviews/m-lab/scraper/106#-Kq9RJKWfsDdMf38Axgi:-Kq9SWTXlY3Kwj_L0gIe:b-7trd33) ([raw file](https://github.com/m-lab/scraper/blob/652eba47e79d720edf2eca323b97f19474957b16/validation/verify-old-vs-new-june2017.sh#L39)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

newfile and oldfile could be compressed according to the logic. But, is that ever a possibility for sidestream logs?
</blockquote></details>

I do not believe it is.

---

*[validation/verify-old-vs-new-june2017.sh, line 43 at r2](https://reviewable.io:443/reviews/m-lab/scraper/106#-Kq9RaxWvq_AyaMY3rvQ:-Kq9SUwcn-msko3UEJds:bvypdif) ([raw file](https://github.com/m-lab/scraper/blob/652eba47e79d720edf2eca323b97f19474957b16/validation/verify-old-vs-new-june2017.sh#L43)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

do we want to exit rather than continue?
</blockquote></details>

Nope. Fixed.

---

*[validation/verify-old-vs-new-june2017.sh, line 88 at r2](https://reviewable.io:443/reviews/m-lab/scraper/106#-Kq9Rs_mjCUbg47ZtQ5Z:-Kq9SdqOtUlYZ2R1dtHH:b-bzbpby) ([raw file](https://github.com/m-lab/scraper/blob/652eba47e79d720edf2eca323b97f19474957b16/validation/verify-old-vs-new-june2017.sh#L88)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Does the old/filelist.txt also need to be sorted?
</blockquote></details>

It already is. The main purpose of the sort is the -u. I thought about using uniq, but for whatever reason that's not what I typed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/106)*

**Comment by pboothe** [comment]
*[validation/verify-old-vs-new-june2017.sh, line 72 at r2](https://reviewable.io:443/reviews/m-lab/scraper/106#-Kq9QgtlYOobLhJ4EJ9w:-Kq9UC_7M-VCBClyiNez:bb6un1j) ([raw file](https://github.com/m-lab/scraper/blob/652eba47e79d720edf2eca323b97f19474957b16/validation/verify-old-vs-new-june2017.sh#L72)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please add a "\" to wrap this line before the `||`.

Please add a comment about why this is necessary (and when it might not be necessary any more).
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/106)*

**Comment by stephen-soltesz** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/106#-:-Kq9U_8q38N530ojK2wG:bnfp4nl)*

**Pull request merged**
