### PR TITLE
Uncompress component files of the tarfile prior to archiving.

### PR DESCRIPTION
**Pull request by pboothe**
Our existing pipeline uncompresses all component files prior to archiving the data. This adds in code to do that.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/scraper/8)

### CODE REVIEW

**Comment by nkinkade** [comment]
I added a few comments to scraper.py.

---

Reviewed 3 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[scraper.py, line 422 at r1](https://reviewable.io:443/reviews/m-lab/scraper/8#-KankeyMrRg-YInEqsvs:-Kankcy8y6ys6RTaSuhT:b-xv769j) ([raw file](https://github.com/m-lab/scraper/blob/3080e43d5f2cd1c9f06ac7e31980989fb216ab32/scraper.py#L422)):*
Should `filename` and `basename` be swapped here? As is, I think it's going to say something like:

> [...] file somefile.gz is the unzipped version of somefile

---

*[scraper.py, line 424 at r1](https://reviewable.io:443/reviews/m-lab/scraper/8#-KanvwhdQ3kSGj20d9Ug:-KanvwhexJ_Jxe26EiE7:b-rr7wz8) ([raw file](https://github.com/m-lab/scraper/blob/3080e43d5f2cd1c9f06ac7e31980989fb216ab32/scraper.py#L424)):*
> ```Python
>             'version of %s', filename, basename)
>         return basename
>     command = [gunzip_binary, '--keep', filename]
> ```

What is the reasoning behind keeping the gzipped file around with `--keep`?

---

*[scraper.py, line 443 at r1](https://reviewable.io:443/reviews/m-lab/scraper/8#-KantfUNSdv-ik5yr-56:-KantfUNSdv-ik5yr-57:b-hqztbc) ([raw file](https://github.com/m-lab/scraper/blob/3080e43d5f2cd1c9f06ac7e31980989fb216ab32/scraper.py#L443)):*
> ```Python
>     """
>     try:
>         return decompress_file(gunzip_binary, filename)
> ```

What is the reasoning behind breaking `attempt_decompression()` and `decompress_file()` into two functions.  This wrapper function accepts the same arguments as `decompress_file()`.

---

*[scraper.py, line 444 at r1](https://reviewable.io:443/reviews/m-lab/scraper/8#-Kanu7L7z4ezlkRpmmvy:-Kanu7L7z4ezlkRpmmvz:b-s94gk1) ([raw file](https://github.com/m-lab/scraper/blob/3080e43d5f2cd1c9f06ac7e31980989fb216ab32/scraper.py#L444)):*
> ```Python
>     try:
>         return decompress_file(gunzip_binary, filename)
>     except DecompressionException as error:
> ```

How does the current pipeline code handle this sort of error, or does it even? I'm wondering if there is ever a case where `.gz` files sometimes end up a resultant `.tgz` file like this one would be doing.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/8#-:-KanxDBvMlbXaZ3tbds-:b7dicqh)*

**Comment by pboothe** [comment]
Review status: 3 of 4 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[scraper.py, line 422 at r1](https://reviewable.io:443/reviews/m-lab/scraper/8#-KankeyMrRg-YInEqsvs:-Kar8k9Eus1RnljY6np3:b-896fix) ([raw file](https://github.com/m-lab/scraper/blob/3080e43d5f2cd1c9f06ac7e31980989fb216ab32/scraper.py#L422)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Should `filename` and `basename` be swapped here? As is, I think it's going to say something like:

> [...] file somefile.gz is the unzipped version of somefile

</blockquote></details>

Done.

---

*[scraper.py, line 424 at r1](https://reviewable.io:443/reviews/m-lab/scraper/8#-KanvwhdQ3kSGj20d9Ug:-Kar93CE38iWYWTxMS1w:b-ucmxwh) ([raw file](https://github.com/m-lab/scraper/blob/3080e43d5f2cd1c9f06ac7e31980989fb216ab32/scraper.py#L424)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

What is the reasoning behind keeping the gzipped file around with `--keep`?
</blockquote></details>

It was helpful during debugging, but you are right that it is no longer required. Fixed.

---

*[scraper.py, line 443 at r1](https://reviewable.io:443/reviews/m-lab/scraper/8#-KantfUNSdv-ik5yr-56:-KarETsYMQMwEqTY_LpN:b-9d8xnc) ([raw file](https://github.com/m-lab/scraper/blob/3080e43d5f2cd1c9f06ac7e31980989fb216ab32/scraper.py#L443)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

What is the reasoning behind breaking `attempt_decompression()` and `decompress_file()` into two functions.  This wrapper function accepts the same arguments as `decompress_file()`.
</blockquote></details>

That's just how it grew. I have simplified things as a result of this comment, and I think they are now a lot better.

---

*[scraper.py, line 444 at r1](https://reviewable.io:443/reviews/m-lab/scraper/8#-Kanu7L7z4ezlkRpmmvy:-KarEAxCWF7d-70L1n5J:br7ny54) ([raw file](https://github.com/m-lab/scraper/blob/3080e43d5f2cd1c9f06ac7e31980989fb216ab32/scraper.py#L444)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

How does the current pipeline code handle this sort of error, or does it even? I'm wondering if there is ever a case where `.gz` files sometimes end up a resultant `.tgz` file like this one would be doing.  
</blockquote></details>

If decompression fails the original compressed file is included, just like here. Or at least that's what the code does. I am unaware of any cases where that code path was triggered in practice, but I am trying to match behavior.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/8)*

**Comment by pboothe** [comment]
PTAL

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/8#-:-KarTLIKKnS3El9VzJhQ:bb71pro)*

**Comment by nkinkade** [comment]
:lgtm: Thanks!

---

Reviewed 1 of 2 files at r2.
Review status: 3 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[scraper.py, line 444 at r1](https://reviewable.io:443/reviews/m-lab/scraper/8#-Kanu7L7z4ezlkRpmmvy:-KarYgeOkCXbDMKn14lY:bfoomgf) ([raw file](https://github.com/m-lab/scraper/blob/3080e43d5f2cd1c9f06ac7e31980989fb216ab32/scraper.py#L444)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

If decompression fails the original compressed file is included, just like here. Or at least that's what the code does. I am unaware of any cases where that code path was triggered in practice, but I am trying to match behavior.
</blockquote></details>

Got it... I just wanted to be sure that leaving the .gz file in the archive was the same behavior the existing scraper would exhibit in the case of a decompression failure.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/8#-:-KarZPzPfSMFmhf_-uGd:b-g2a5fb)*

**Comment by nkinkade** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/8)*

**Comment by pboothe** [comment]
Ack-ing comment to make reviewable happy.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[scraper.py, line 444 at r1](https://reviewable.io:443/reviews/m-lab/scraper/8#-Kanu7L7z4ezlkRpmmvy:-Karg8wGocGLx6jIo1_Q:b-54snbz) ([raw file](https://github.com/m-lab/scraper/blob/3080e43d5f2cd1c9f06ac7e31980989fb216ab32/scraper.py#L444)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Got it... I just wanted to be sure that leaving the .gz file in the archive was the same behavior the existing scraper would exhibit in the case of a decompression failure.
</blockquote></details>

Acknowledged.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/8#-:-KargCtcUQtq1f7414OA:boa0mpz)*

**Comment by pboothe** [comment]
Reviewable is happy but travis' version of gzip doesn't match the one on my workstation. I'll make the test pass and submit.

**Pull request merged**
