### PR TITLE
updates the operator repo submodle to acfe5f4

### PR DESCRIPTION
**Pull request by critzo**
This PR updates scraper's operator submodule to the latest commit. @stephen-soltesz PTAL?

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/scraper/202)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
I can't approve this while the build is broken -- @pboothe https://travis-ci.org/m-lab/scraper/builds/311612336#L6117 -- is this stack trace during tests due to a version change?

**Comment by pboothe** [comment]
Investigating now. I may have a flaky end-to-end test.

**Comment by pboothe** [comment]
Yep, flaky tests. Filing an issue and I will fix very soon. Flaky tests really piss me off for reasons best explicated in this koan: http://thecodelesscode.com/case/225

**Comment by stephen-soltesz** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/202#-:-L-hnlNDzGgaOCY7txzQ:bnfp4nl)*

**Comment by pboothe** [comment]
This was never merged and has been superseded by later merges.

**Pull request closed without merging**
