### PR TITLE
Tarfiles on volumes

### PR DESCRIPTION
**Pull request by pboothe**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/scraper/50)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[deploy.sh, line 119 at r2](https://reviewable.io:443/reviews/m-lab/scraper/50#-Kl5QdZNS8yjd3Jzvu2R:-Kl5QdZNS8yjd3Jzvu2S:b-kr4j2y) ([raw file](https://github.com/m-lab/scraper/blob/56d49dc2bc51d98f0171112def5a5117080117b5/deploy.sh#L119)):*
> ```Shell
> kubectl apply -f k8s/storage-class.yml
> 
> exit 1
> ```

Maybe remove before commit?

---

*[scraper.py, line 430 at r2](https://reviewable.io:443/reviews/m-lab/scraper/50#-Kl5RHDkYM3esu9P93I6:-Kl5RHDkYM3esu9P93I7:b86b0u8) ([raw file](https://github.com/m-lab/scraper/blob/56d49dc2bc51d98f0171112def5a5117080117b5/scraper.py#L430)):*
> ```Python
>       A tuple of the name of the tarfile created, the most recent mtime of
>       any tarfile's component files, and the number of files in the tarfile
>     """
> ```

This may now raise `SysExit`?

---

*[k8s/deploy_template.yml, line 75 at r2](https://reviewable.io:443/reviews/m-lab/scraper/50#-Kl5SOnBEBgxXdTUATaY:-Kl5SOnBEBgxXdTUATaZ:b-1fv1ml) ([raw file](https://github.com/m-lab/scraper/blob/56d49dc2bc51d98f0171112def5a5117080117b5/k8s/deploy_template.yml#L75)):*
> ```YAML
>             name: volume-{{site_safe}}-{{node_safe}}-{{experiment_safe}}-{{rsync_module_safe}}
>           - mountPath: /tarfiles
>             name: volume-{{site_safe}}-{{node_safe}}-{{experiment_safe}}-{{rsync_module_safe}}
> ```

Just for the record, we discussed in person: both `/scraper_data` and `/tarfiles` will point to the same directory at the root of the `volume`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/50)*

**Comment by pboothe** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[deploy.sh, line 119 at r2](https://reviewable.io:443/reviews/m-lab/scraper/50#-Kl5QdZNS8yjd3Jzvu2R:-Kl5WKVn90LHf0jyCT__:be075yv) ([raw file](https://github.com/m-lab/scraper/blob/56d49dc2bc51d98f0171112def5a5117080117b5/deploy.sh#L119)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Maybe remove before commit?
</blockquote></details>

Will do. This was here for today's debugging adventure.

---

*[scraper.py, line 430 at r2](https://reviewable.io:443/reviews/m-lab/scraper/50#-Kl5RHDkYM3esu9P93I6:-Kl5WXYyI-rmw9PN9aQT:byhp1ci) ([raw file](https://github.com/m-lab/scraper/blob/56d49dc2bc51d98f0171112def5a5117080117b5/scraper.py#L430)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

This may now raise `SysExit`?
</blockquote></details>

It always could. But now the `finally:` clauses won't sometimes hide that area.

---

*[k8s/deploy_template.yml, line 75 at r2](https://reviewable.io:443/reviews/m-lab/scraper/50#-Kl5SOnBEBgxXdTUATaY:-Kl5WlEYVIuQHrWinski:b-97hr5d) ([raw file](https://github.com/m-lab/scraper/blob/56d49dc2bc51d98f0171112def5a5117080117b5/k8s/deploy_template.yml#L75)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Just for the record, we discussed in person: both `/scraper_data` and `/tarfiles` will point to the same directory at the root of the `volume`.
</blockquote></details>

Yes, I agree.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/50)*

**Comment by stephen-soltesz** [comment]
:lgtm:

---

Review status: 5 of 6 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/50#-:-Kl5YBh9IhHRVx5PJ8cW:bnfp4nl)*

**Comment by stephen-soltesz** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/50)*

**Pull request merged**
