### PR TITLE
Spreadsheet + Bucket upload

### PR DESCRIPTION
**Pull request by pboothe**
Everything seems to work.  Check it out!

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/scraper/4)

### CODE REVIEW

**Comment by nkinkade** [comment]
Reviewed 3 of 6 files at r1.
Review status: 3 of 6 files reviewed at latest revision, 8 unresolved discussions.

---

*[requirements.txt, line 10 at r1](https://reviewable.io:443/reviews/m-lab/scraper/4#-KXvJL5zz-qZWwmMp6_o:-KXvJL6-hcqGbGAvRL5T:b-oc0du8) ([raw file](https://github.com/m-lab/scraper/blob/a1054c23681cfc7603c15923bb801c6e1fb5f1c7/requirements.txt#L10)):*
> ```
> autopep8
> docformatter
> dateparser
> ```

Out of curiosity, you've added the above new modules to this requirements document, but haven't actually imported any of them to them to `scraper.py` or `scraper_test.py`.  Are these added requirements just anticipating things you expect do to but havn't yet? Additionally, I see you've added a number of new modules to `scraper.py` (e.g., oauth2client) that haven't been added here as requirements.

---

*[scraper.py, line 169 at r1](https://reviewable.io:443/reviews/m-lab/scraper/4#-KXvoYihszSGYbi3HR9b:-KXvoYihszSGYbi3HR9c:bsjw9r) ([raw file](https://github.com/m-lab/scraper/blob/a1054c23681cfc7603c15923bb801c6e1fb5f1c7/scraper.py#L169)):*
> ```Python
>         metavar='BUCKET',
>         type=str,
>         default='mlab-storage-scraper-test',
> ```

Since this (and also the`--spreadsheet` option) is something of a variable, would it make sense to define this as a constant?

Top of file: `GCS_BUCKET = 'mlab-storage-scraper-test'`
Here: `default=GCS_BUCKET`

---

*[scraper.py, line 197 at r1](https://reviewable.io:443/reviews/m-lab/scraper/4#-KXvt6ZCzOpeQ9gbskMI:-KXvt6ZDTu2XR72PpuD0:bqrtmv7) ([raw file](https://github.com/m-lab/scraper/blob/a1054c23681cfc7603c15923bb801c6e1fb5f1c7/scraper.py#L197)):*
> ```Python
>     try:
>         logging.info('rsync file list discovery from %s', rsync_url)
>         command = [rsync_binary, '--list-only', '-r'] + \
> ```

Could we change `-r` to `--recursive` so the options is more self-explanatory?

---

*[scraper.py, line 452 at r1](https://reviewable.io:443/reviews/m-lab/scraper/4#-KXvuyXdpftIWUhQ9akm:-KXvuyXdpftIWUhQ9akn:b424bix) ([raw file](https://github.com/m-lab/scraper/blob/a1054c23681cfc7603c15923bb801c6e1fb5f1c7/scraper.py#L452)):*
> ```Python
> 
> def upload_tarfile(service, tgz_filename, date, bucket):  # pragma: no cover
>     """Uploads a tarfile to bigstore for later processing."""
> ```

Is bigstore equal to Google Cloud Storage?

Also, are you planning to complete the docstring for this function, including all the ones after this one that aren't complete?

---

*[scraper.py, line 502 at r1](https://reviewable.io:443/reviews/m-lab/scraper/4#-KXw68LKbmo7J89eRqA1:-KXw68LKbmo7J89eRqA2:b-1emsvq) ([raw file](https://github.com/m-lab/scraper/blob/a1054c23681cfc7603c15923bb801c6e1fb5f1c7/scraper.py#L502)):*
> ```Python
>             return cell_to_date_or_die(date)
>     logging.warning('No row found for %s', rsync_url)
>     return default_date
> ```

Why return an arbitrarily old date at this point? Is this as a safeguard such that newer files will never be deleted if the row didn't match? It seems like an error condition if `rsync_url` isn't found in the data from the spreadsheet.

---

*[scraper.py, line 510 at r1](https://reviewable.io:443/reviews/m-lab/scraper/4#-KXw9LJalzXb7rzFxW06:-KXw9LJalzXb7rzFxW07:boe8nn1) ([raw file](https://github.com/m-lab/scraper/blob/a1054c23681cfc7603c15923bb801c6e1fb5f1c7/scraper.py#L510)):*
> ```Python
> 
>     The row and column of the cell are determined by the rsync_url and column
>     values, respectively.  If no such row exists, then one willbe created.
> ```

Typo: s/willbe/will be/

---

*[scraper.py, line 519 at r1](https://reviewable.io:443/reviews/m-lab/scraper/4#-KXwA1QQ-zOs8DX8kNfp:-KXwA1QQ-zOs8DX8kNfq:b41km8r) ([raw file](https://github.com/m-lab/scraper/blob/a1054c23681cfc7603c15923bb801c6e1fb5f1c7/scraper.py#L519)):*
> ```Python
>         sys.exit(1)
>     header = values[0]
>     rsync_index = header.index(u'dropboxrsyncaddress')
> ```

From this line up to `worksheet_name =` appears to be essentially identical to what is done in `get_progress_from_spreadsheet()`. Instead of the duplication, could these steps be moved in the `get_spreadsheet_data` function?

---

*[scraper.py, line 552 at r1](https://reviewable.io:443/reviews/m-lab/scraper/4#-KXwHyi2UWEiCYG6ii4U:-KXwHyi2UWEiCYG6ii4V:b-x32f6v) ([raw file](https://github.com/m-lab/scraper/blob/a1054c23681cfc7603c15923bb801c6e1fb5f1c7/scraper.py#L552)):*
> ```Python
>     date_str = 'x%d-%02d-%02d' % (date.year, date.month, date.day)
>     update_spreadsheet_data(service, spreadsheet, rsync_url,
>                             'lastsuccessfulcollection', date_str)
> ```

Though they are unlikely to ever change as long as we use this barbaric spreadsheet, something inside me pushes back about having the column names embedded deeply with the code instead of defined as a constant.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/4)*

**Comment by pboothe** [comment]
Review status: 3 of 6 files reviewed at latest revision, 8 unresolved discussions.

---

*[requirements.txt, line 10 at r1](https://reviewable.io:443/reviews/m-lab/scraper/4#-KXvJL5zz-qZWwmMp6_o:-KY-C_A-cUalQ4r8_ddK:b7obyr9) ([raw file](https://github.com/m-lab/scraper/blob/a1054c23681cfc7603c15923bb801c6e1fb5f1c7/requirements.txt#L10)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Out of curiosity, you've added the above new modules to this requirements document, but haven't actually imported any of them to them to `scraper.py` or `scraper_test.py`.  Are these added requirements just anticipating things you expect do to but havn't yet? Additionally, I see you've added a number of new modules to `scraper.py` (e.g., oauth2client) that haven't been added here as requirements.
</blockquote></details>

dateparser is vestigial, but the others are all actually used. mock, coveralls, unify, autoflake, autopep8, and docformatter are all part of the tests and pre-commit hooks. google-api-python-client provides the oauth2 stuff. It kinda sucks that pip package names don't necessarily correspond to the name of the thing being imported.

---

*[scraper.py, line 169 at r1](https://reviewable.io:443/reviews/m-lab/scraper/4#-KXvoYihszSGYbi3HR9b:-KY-D9OI3sAb_Hjk_9Qj:b-2ori7e) ([raw file](https://github.com/m-lab/scraper/blob/a1054c23681cfc7603c15923bb801c6e1fb5f1c7/scraper.py#L169)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Since this (and also the`--spreadsheet` option) is something of a variable, would it make sense to define this as a constant?

Top of file: `GCS_BUCKET = 'mlab-storage-scraper-test'`
Here: `default=GCS_BUCKET`
</blockquote></details>

Could do, but that seems wrong? Global variables, even constant ones, have a cost. It seems like a useless expenditure of mental energy on the part of the writer and reader to create a global variable that is used only once, and that once is in a place that is pretty easy to understand.

---

*[scraper.py, line 197 at r1](https://reviewable.io:443/reviews/m-lab/scraper/4#-KXvt6ZCzOpeQ9gbskMI:-KY-DJy8NW9HBHsP0G32:bb7f2mf) ([raw file](https://github.com/m-lab/scraper/blob/a1054c23681cfc7603c15923bb801c6e1fb5f1c7/scraper.py#L197)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Could we change `-r` to `--recursive` so the options is more self-explanatory?
</blockquote></details>

done

---

*[scraper.py, line 452 at r1](https://reviewable.io:443/reviews/m-lab/scraper/4#-KXvuyXdpftIWUhQ9akm:-KY-F1GWn14BsyCGrchu:b-clcu8z) ([raw file](https://github.com/m-lab/scraper/blob/a1054c23681cfc7603c15923bb801c6e1fb5f1c7/scraper.py#L452)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Is bigstore equal to Google Cloud Storage?

Also, are you planning to complete the docstring for this function, including all the ones after this one that aren't complete?
</blockquote></details>

All instances of Google-internal name bigstore have been changed to Google Cloud Storage

Added args to many of the docstrings. I go back and forth about how valuable it is to add so much documentation to a function that the documentation is longer than the function body. I'll spot you that `upload_tarfile` might be able to use the help (so I updated it), but documenting `cell_to_date_or_die` beyond its single line really does seem like overkill, so I didn't change the docs there.  Other functions have had their documentation updated to an appropriate degree.

---

*[scraper.py, line 502 at r1](https://reviewable.io:443/reviews/m-lab/scraper/4#-KXw68LKbmo7J89eRqA1:-KY-FFA_b0Yl2Zr6Fexk:b-tq8kh0) ([raw file](https://github.com/m-lab/scraper/blob/a1054c23681cfc7603c15923bb801c6e1fb5f1c7/scraper.py#L502)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Why return an arbitrarily old date at this point? Is this as a safeguard such that newer files will never be deleted if the row didn't match? It seems like an error condition if `rsync_url` isn't found in the data from the spreadsheet.
</blockquote></details>

It's also what happens when there is a new site. The arbitrary old date is chosen to be jan 1 before the first MLab machines were turned up, and is therefore earlier than any test that might ever be downloaded from the MLab infrastructure

---

*[scraper.py, line 510 at r1](https://reviewable.io:443/reviews/m-lab/scraper/4#-KXw9LJalzXb7rzFxW06:-KY-yMsto3mIa898vwZ4:b-896fix) ([raw file](https://github.com/m-lab/scraper/blob/a1054c23681cfc7603c15923bb801c6e1fb5f1c7/scraper.py#L510)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Typo: s/willbe/will be/
</blockquote></details>

Done.

---

*[scraper.py, line 519 at r1](https://reviewable.io:443/reviews/m-lab/scraper/4#-KXwA1QQ-zOs8DX8kNfp:-KY-HBe6tfsOKBlg4wTA:b-x4981t) ([raw file](https://github.com/m-lab/scraper/blob/a1054c23681cfc7603c15923bb801c6e1fb5f1c7/scraper.py#L519)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

From this line up to `worksheet_name =` appears to be essentially identical to what is done in `get_progress_from_spreadsheet()`. Instead of the duplication, could these steps be moved in the `get_spreadsheet_data` function?
</blockquote></details>

You were right to smell that there was a problem. I addressed the problem differently.

---

*[scraper.py, line 552 at r1](https://reviewable.io:443/reviews/m-lab/scraper/4#-KXwHyi2UWEiCYG6ii4U:-KY-unCmwp-YoznwBuOm:b-mxyims) ([raw file](https://github.com/m-lab/scraper/blob/a1054c23681cfc7603c15923bb801c6e1fb5f1c7/scraper.py#L552)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Though they are unlikely to ever change as long as we use this barbaric spreadsheet, something inside me pushes back about having the column names embedded deeply with the code instead of defined as a constant.
</blockquote></details>

I get it. But is it really a win to do:
```python
LASTSUCCESSFULCOLLECTION = 'lastsuccessfulcollection'

...
       update_spreadsheet_data(service, spreadsheet, rsync_url,
                            LASTSUCCESSFULCOLLECTION, date_str)
```
?

I don't think it is, but I am willing to be persuaded.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/4)*

**Comment by nkinkade** [comment]
Review status: 3 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[scraper.py, line 452 at r1](https://reviewable.io:443/reviews/m-lab/scraper/4#-KXvuyXdpftIWUhQ9akm:-KY0SmYIlwDZH_EK4Oo1:b-r5wgvl) ([raw file](https://github.com/m-lab/scraper/blob/a1054c23681cfc7603c15923bb801c6e1fb5f1c7/scraper.py#L452)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

All instances of Google-internal name bigstore have been changed to Google Cloud Storage

Added args to many of the docstrings. I go back and forth about how valuable it is to add so much documentation to a function that the documentation is longer than the function body. I'll spot you that `upload_tarfile` might be able to use the help (so I updated it), but documenting `cell_to_date_or_die` beyond its single line really does seem like overkill, so I didn't change the docs there.  Other functions have had their documentation updated to an appropriate degree.
</blockquote></details>

Regarding docstrings, whatever you prefer. I do know that in the past StephenZ has been fairly insistent on me adding dostrings to everything regardless, at least that has been my impression.  docstrings also have value outside the context of someone reading through the code, if they were, for example, extracted by pydoc.

---

*[scraper.py, line 552 at r1](https://reviewable.io:443/reviews/m-lab/scraper/4#-KXwHyi2UWEiCYG6ii4U:-KY0VPGYPVL2MPQHVzCm:b-xdifx5) ([raw file](https://github.com/m-lab/scraper/blob/a1054c23681cfc7603c15923bb801c6e1fb5f1c7/scraper.py#L552)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

I get it. But is it really a win to do:
```python
LASTSUCCESSFULCOLLECTION = 'lastsuccessfulcollection'

...
       update_spreadsheet_data(service, spreadsheet, rsync_url,
                            LASTSUCCESSFULCOLLECTION, date_str)
```
?

I don't think it is, but I am willing to be persuaded.
</blockquote></details>

I'm open to deferring to your experience here, and the example you gave definitely seems rather ridiculous.  My general impression is that it's not ideal to embed variable data inside code. It could be argued that the column names are not, in fact, variable, since there is very little chance they will ever change.  Then again, I'm sure most programmers have had at least one bad experience from hardcoding a database column name into code... at least I know I have.  In any case, I was just pointing out something that seemed slightly awkward to me, but definitely do whatever makes the most sense here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/4)*

**Comment by nkinkade** [comment]
:lgtm: ... with the understanding that on the question of docstrings and constants I'll just defer to your experience.

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/4#-:-KY0_jkUCq0B5b6qgPlK:b-lj37nu)*

**Comment by pboothe** [comment]
Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[scraper.py, line 452 at r1](https://reviewable.io:443/reviews/m-lab/scraper/4#-KXvuyXdpftIWUhQ9akm:-KYEbn1QmY3vv0WYMv0b:b-f6bjbt) ([raw file](https://github.com/m-lab/scraper/blob/a1054c23681cfc7603c15923bb801c6e1fb5f1c7/scraper.py#L452)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Regarding docstrings, whatever you prefer. I do know that in the past StephenZ has been fairly insistent on me adding dostrings to everything regardless, at least that has been my impression.  docstrings also have value outside the context of someone reading through the code, if they were, for example, extracted by pydoc.
</blockquote></details>

Totally. The issue is when the function name is sufficient documentation and when it is not. For example, if the single argument function `cell_to_date_or_die(cell_text)` does anything other than convert the contents of a cell to a date and/or call `sys.exit`, then it should be documented.  The more generic and wishy-washy a name is, and the more arguments a function takes, the more likely full documentation is needed, so `upload_tarfile` got the whole nine yards.  

For comments in general, the more likely someone is to want to know why something is the way it is, the more likely you need a comment. That is, if the answer to "why can't I delete this line of code?" isn't obvious, it should have a comment explaining what it does.  When reading in-code comments, I sometimes prefix them in my head with "Please don't delete this chunk because without it we couldn't ..." and then read the comment. If the comment doesn't make sense with that prefix, then I rewrite it or delete it.

---

*[scraper.py, line 552 at r1](https://reviewable.io:443/reviews/m-lab/scraper/4#-KXwHyi2UWEiCYG6ii4U:-KYEatbiqPlq-0cPtrdW:b-3simlt) ([raw file](https://github.com/m-lab/scraper/blob/a1054c23681cfc7603c15923bb801c6e1fb5f1c7/scraper.py#L552)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

I'm open to deferring to your experience here, and the example you gave definitely seems rather ridiculous.  My general impression is that it's not ideal to embed variable data inside code. It could be argued that the column names are not, in fact, variable, since there is very little chance they will ever change.  Then again, I'm sure most programmers have had at least one bad experience from hardcoding a database column name into code... at least I know I have.  In any case, I was just pointing out something that seemed slightly awkward to me, but definitely do whatever makes the most sense here.
</blockquote></details>

I tried to figure out what a good rule of thumb might be, and I came up with: "If the constant is only referred to once, then you probably do not need a name for it, and if the constant is referred to in multiple functions, then you likely do need a name for it."  Both `'lastsuccessfulcollection'` and `'dropboxrsyncaddress'` appeared in multiple functions, so I have given them a name inside the `Spreadsheet` class.  `'mlab-storage-scraper-test'` and `'143pU25GJidW2KZ_93hgzHdqTqq22wgdxR_3tt3dvrJY'`each only appeared once in one function, so I have let them be.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/4)*

**Pull request merged**
