### PR TITLE
Fix staging crashloop

### PR DESCRIPTION
**Pull request by pboothe**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/scraper/146)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
:lgtm: - with what sounds like the removal of `run_tests_with_emulator.sh`.

---

Reviewed 7 of 8 files at r1.
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[run_tests_with_emulator.sh, line 1 at r1](https://reviewable.io:443/reviews/m-lab/scraper/146#-KvDHwdbhkcj4b9aAKBw:-KvDHND-3tQWD2znGGv7:bnh8kg1) ([raw file](https://github.com/m-lab/scraper/blob/e4d7259b496eb248a1d9540cf4d4c94fdf9a3055/run_tests_with_emulator.sh#L1)):*
> ```Shell
> #!/bin/bash
> ```

From in person conversation, it sounds like this file is no longer necessary.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/146#-:-KvDI17fi64dSfioy0Y0:bl7yppc)*

**Comment by stephen-soltesz** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/146)*

**Comment by pboothe** [comment]
Reviewable is not yet happy, despite the :lgtm: ? 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

*[run_tests_with_emulator.sh, line 1 at r1](https://reviewable.io:443/reviews/m-lab/scraper/146#-KvDHwdbhkcj4b9aAKBw:-KvDPt2o73bHC22n8lc-:b-896fix) ([raw file](https://github.com/m-lab/scraper/blob/e4d7259b496eb248a1d9540cf4d4c94fdf9a3055/run_tests_with_emulator.sh#L1)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

From in person conversation, it sounds like this file is no longer necessary.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/146#-:-KvDPuEpaZw6DscAQEqu:ba2dz9c)*

**Comment by pboothe** [comment]
NM, I just needed to click "done" on your comment.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/146#-:-KvDQ05U--Rg_nOGRrAx:b-nop97e)*

**Pull request merged**
