### PR TITLE
Repeated files bug

### PR DESCRIPTION
**Pull request by pboothe**
Times should be monotonic now.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/scraper/177)

### CODE REVIEW

**Comment by gfr10598** [comment]
Some suggestions for improving readability.  I'm finding the names of things pretty obscure and confusing.  Still working on last block of code.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/177#-:-KxFG5kzx-m0SCFvGoIN:b-je9mji)*

**Comment by gfr10598** [comment]
Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[scraper.py, line 324 at r1](https://reviewable.io:443/reviews/m-lab/scraper/177#-KxFDvx3yzr-7lDhF2-3:-KxFDvx3yzr-7lDhF2-4:bl57rwc) ([raw file](https://github.com/m-lab/scraper/blob/f09a7801d426703d06c89c81191af151d6da31a2/scraper.py#L324)):*
> ```Python
> 
> 
> def must_upload_up_to():
> ```

may_upload_up_to ?  Seems like this is the latest date that it is ok to upload to, but it it not mandatory?

Change the name or change the comment?

---

*[scraper.py, line 752 at r1](https://reviewable.io:443/reviews/m-lab/scraper/177#-KxFEtIqdtupkht6pa5F:-KxFEtIqdtupkht6pa5G:bqa8da) ([raw file](https://github.com/m-lab/scraper/blob/f09a7801d426703d06c89c81191af151d6da31a2/scraper.py#L752)):*
> ```Python
>         self.update_data(self.LAST_COLLECTION_KEY, unicode(text, 'UTF-8'))
> 
>     def update_mtime(self, mtime):
> ```

update_datastore_mtime  ?

---

*[scraper.py, line 756 at r1](https://reviewable.io:443/reviews/m-lab/scraper/177#-KxFEDn4CA6M31GxRnrc:-KxFEDn4CA6M31GxRnrd:b-uqfmty) ([raw file](https://github.com/m-lab/scraper/blob/f09a7801d426703d06c89c81191af151d6da31a2/scraper.py#L756)):*
> ```Python
>         self.update_data(self.MTIME_KEY, mtime)
> 
>     def on_upload_success(self, mtime_datetime):
> ```

What is mtime_datetime?  Date/time up to which OK to delete?  Date/time of last test file uploaded?  Something else?
Suggest improving the name, and clarifying in comment.

---

*[scraper.py, line 866 at r1](https://reviewable.io:443/reviews/m-lab/scraper/177#-KxFFFZhoq2RH2h7uFnD:-KxFFFZhoq2RH2h7uFnE:b-3emmj2) ([raw file](https://github.com/m-lab/scraper/blob/f09a7801d426703d06c89c81191af151d6da31a2/scraper.py#L866)):*
> ```Python
>     high_water_mark = sync_status.get_last_archived_mtime()
>     most_recent_allowable_mtime = datetime.datetime.now() - args.data_wait_time
>     if upload_is_recommended(high_water_mark, most_recent_allowable_mtime,
> ```

nit:  if should_upload(...) ?

---

*[scraper.py, line 917 at r1](https://reviewable.io:443/reviews/m-lab/scraper/177#-KxFFnbwTxyzKShmqG7Y:-KxFFnbwTxyzKShmqG7Z:b-skszxl) ([raw file](https://github.com/m-lab/scraper/blob/f09a7801d426703d06c89c81191af151d6da31a2/scraper.py#L917)):*
> ```Python
>     """Tar and upload local data.
> 
>     Tar up what we have for each unarchived day that is sufficiently in the past
> ```

update  'unarchived day'

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/177)*

**Comment by gfr10598** [comment]
Reviewed 1 of 3 files at r1.
Review status: 1 of 3 files reviewed at latest revision, 10 unresolved discussions.

---

*[scraper.py, line 328 at r1](https://reviewable.io:443/reviews/m-lab/scraper/177#-KxFIEEFATbi8j_BltgN:-KxFIEEFATbi8j_BltgO:baro194) ([raw file](https://github.com/m-lab/scraper/blob/f09a7801d426703d06c89c81191af151d6da31a2/scraper.py#L328)):*
> So this should always be
>     one second before midnight either yesterday or the day before, depending on
>     how late in the day it is.
Update comment?

---

*[scraper.py, line 740 at r1](https://reviewable.io:443/reviews/m-lab/scraper/177#-KxFJ9g-TWcA0rjPrR-s:-KxFJ9g-TWcA0rjPrR-t:b-7j68fa) ([raw file](https://github.com/m-lab/scraper/blob/f09a7801d426703d06c89c81191af151d6da31a2/scraper.py#L740)):*
> ```Python
>         """Updates the date before which it is safe to delete data."""
>         date_str = u'x%d-%02d-%02d' % (date.year, date.month, date.day)
>         self.update_data(self.COLLECTION_KEY, date_str)
> ```

Drop this now?  It is confusing to have both.

---

*[scraper.py, line 753 at r1](https://reviewable.io:443/reviews/m-lab/scraper/177#-KxFJFsmc-I3cWbIi9O0:-KxFJFsmc-I3cWbIi9O1:bnxm1xu) ([raw file](https://github.com/m-lab/scraper/blob/f09a7801d426703d06c89c81191af151d6da31a2/scraper.py#L753)):*
> ```Python
> 
>     def update_mtime(self, mtime):
>         """Updates the mtime column in cloud datastore."""
> ```

Expand this comment about what exactly this column is?

---

*[scraper.py, line 928 at r1](https://reviewable.io:443/reviews/m-lab/scraper/177#-KxFHAvKeGTolnGJyQNO:-KxFHAvKeGTolnGJyQNP:bnfe0h0) ([raw file](https://github.com/m-lab/scraper/blob/f09a7801d426703d06c89c81191af151d6da31a2/scraper.py#L928)):*
> ```Python
>     earliest_time = sync_status.get_last_archived_mtime()
>     if candidate_last_archived_mtime < earliest_time:  # pragma: no cover
>         logging.warning('high water mark (%s) is higher than the requested '
> ```

Invert this message? ...  'candidate max mtime (%s) is less than high water mark (%s)'

---

*[scraper.py, line 954 at r1](https://reviewable.io:443/reviews/m-lab/scraper/177#-KxFHxWdyPufWJllgu2p:-KxFHxWdyPufWJllgu2q:b-dy0iuy) ([raw file](https://github.com/m-lab/scraper/blob/f09a7801d426703d06c89c81191af151d6da31a2/scraper.py#L954)):*
> ```Python
>     FILES_UPLOADED.labels(
>         rsync_host_module='%s-%s-%s' % (node, site, args.rsync_module),
>         day_of_week=day_of_week(candidate_last_archived_mtime)).inc(
> ```

is candidate_last_archived_time ever equal to midnight?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/177)*

**Comment by gfr10598** [comment]
Review status: 1 of 3 files reviewed at latest revision, 10 unresolved discussions.

---

*[scraper.py, line 740 at r1](https://reviewable.io:443/reviews/m-lab/scraper/177#-KxFJ9g-TWcA0rjPrR-s:-KxFJatHgCZnqYIkjKdk:bzgqggp) ([raw file](https://github.com/m-lab/scraper/blob/f09a7801d426703d06c89c81191af151d6da31a2/scraper.py#L740)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Drop this now?  It is confusing to have both.
</blockquote></details>

Maybe populate it first with "obsolete" or "deprecated", and then remove this code later?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/177)*

**Comment by gfr10598** [comment]
Review status: 1 of 3 files reviewed at latest revision, 11 unresolved discussions.

---

*[scraper.py, line 607 at r1](https://reviewable.io:443/reviews/m-lab/scraper/177#-KxFKLZLlvBta3gfSFtV:-KxFKLZLlvBta3gfSFtW:brzfgq) ([raw file](https://github.com/m-lab/scraper/blob/f09a7801d426703d06c89c81191af151d6da31a2/scraper.py#L607)):*
> ```Python
> 
> 
> def delete_datafiles_up_to(directory, max_mtime):
> ```

delete_local_datafiles_up_to

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/177)*

**Comment by gfr10598** [comment]
Reviewed 2 of 3 files at r1.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/177)*

**Comment by pboothe** [comment]
PTAL

---

Review status: 1 of 3 files reviewed at latest revision, 11 unresolved discussions.

---

*[scraper.py, line 324 at r1](https://reviewable.io:443/reviews/m-lab/scraper/177#-KxFDvx3yzr-7lDhF2-3:-KxFO3f2T2_-4CCIW9e9:b-896fix) ([raw file](https://github.com/m-lab/scraper/blob/f09a7801d426703d06c89c81191af151d6da31a2/scraper.py#L324)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

may_upload_up_to ?  Seems like this is the latest date that it is ok to upload to, but it it not mandatory?

Change the name or change the comment?
</blockquote></details>

Done.

---

*[scraper.py, line 328 at r1](https://reviewable.io:443/reviews/m-lab/scraper/177#-KxFIEEFATbi8j_BltgN:-KxFOAeFg2thIsZODhAn:bnlel12) ([raw file](https://github.com/m-lab/scraper/blob/f09a7801d426703d06c89c81191af151d6da31a2/scraper.py#L328)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

> So this should always be
>     one second before midnight either yesterday or the day before, depending on
>     how late in the day it is.
Update comment?
</blockquote></details>

Nope, it's still correct.

---

*[scraper.py, line 607 at r1](https://reviewable.io:443/reviews/m-lab/scraper/177#-KxFKLZLlvBta3gfSFtV:-KxFOOZ0EmWUd9CRLw5L:b-896fix) ([raw file](https://github.com/m-lab/scraper/blob/f09a7801d426703d06c89c81191af151d6da31a2/scraper.py#L607)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

delete_local_datafiles_up_to
</blockquote></details>

Done.

---

*[scraper.py, line 740 at r1](https://reviewable.io:443/reviews/m-lab/scraper/177#-KxFJ9g-TWcA0rjPrR-s:-KxFOk3thf4_eENNXY-L:b-896fix) ([raw file](https://github.com/m-lab/scraper/blob/f09a7801d426703d06c89c81191af151d6da31a2/scraper.py#L740)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Maybe populate it first with "obsolete" or "deprecated", and then remove this code later?
</blockquote></details>

Done.

---

*[scraper.py, line 752 at r1](https://reviewable.io:443/reviews/m-lab/scraper/177#-KxFEtIqdtupkht6pa5F:-KxFOmJPDRmlf1PhE398:beaqvl4) ([raw file](https://github.com/m-lab/scraper/blob/f09a7801d426703d06c89c81191af151d6da31a2/scraper.py#L752)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

update_datastore_mtime  ?
</blockquote></details>

Everything in this object is datastore data.  Adding `_datastore` to every method seems silly?

---

*[scraper.py, line 753 at r1](https://reviewable.io:443/reviews/m-lab/scraper/177#-KxFJFsmc-I3cWbIi9O0:-KxFP7vqyND2Yzu31TV7:b-896fix) ([raw file](https://github.com/m-lab/scraper/blob/f09a7801d426703d06c89c81191af151d6da31a2/scraper.py#L753)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Expand this comment about what exactly this column is?
</blockquote></details>

Done.

---

*[scraper.py, line 756 at r1](https://reviewable.io:443/reviews/m-lab/scraper/177#-KxFEDn4CA6M31GxRnrc:-KxJ5TnqFsY8tTW_Pr3q:b-896fix) ([raw file](https://github.com/m-lab/scraper/blob/f09a7801d426703d06c89c81191af151d6da31a2/scraper.py#L756)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

What is mtime_datetime?  Date/time up to which OK to delete?  Date/time of last test file uploaded?  Something else?
Suggest improving the name, and clarifying in comment.
</blockquote></details>

Done.

---

*[scraper.py, line 866 at r1](https://reviewable.io:443/reviews/m-lab/scraper/177#-KxFFFZhoq2RH2h7uFnD:-KxJ5bWrpAzEG8H4Hs4E:b-896fix) ([raw file](https://github.com/m-lab/scraper/blob/f09a7801d426703d06c89c81191af151d6da31a2/scraper.py#L866)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

nit:  if should_upload(...) ?
</blockquote></details>

Done.

---

*[scraper.py, line 917 at r1](https://reviewable.io:443/reviews/m-lab/scraper/177#-KxFFnbwTxyzKShmqG7Y:-KxJ5pxWBWn7YHx6Hwe1:b-896fix) ([raw file](https://github.com/m-lab/scraper/blob/f09a7801d426703d06c89c81191af151d6da31a2/scraper.py#L917)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

update  'unarchived day'
</blockquote></details>

Done.

---

*[scraper.py, line 928 at r1](https://reviewable.io:443/reviews/m-lab/scraper/177#-KxFHAvKeGTolnGJyQNO:-KxJ65kUZ6jw0hTEjJE_:b-896fix) ([raw file](https://github.com/m-lab/scraper/blob/f09a7801d426703d06c89c81191af151d6da31a2/scraper.py#L928)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Invert this message? ...  'candidate max mtime (%s) is less than high water mark (%s)'
</blockquote></details>

Done.

---

*[scraper.py, line 954 at r1](https://reviewable.io:443/reviews/m-lab/scraper/177#-KxFHxWdyPufWJllgu2p:-KxJ6BYwoOi6LG2iwRKy:byo3mda) ([raw file](https://github.com/m-lab/scraper/blob/f09a7801d426703d06c89c81191af151d6da31a2/scraper.py#L954)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

is candidate_last_archived_time ever equal to midnight?
</blockquote></details>

Could be, but midnight is the beginning of the next day, not the end of the current day.  "Midnight on Tuesday" is, according to datetime, the very first instant of a Tuesday instead of the very last. At second granularities, 23:59:59 is the last possible time on any day.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/177#-:-KxJBQftey7aJ5UM_L5t:bb71pro)*

**Comment by gfr10598** [comment]
:lgtm:

---

Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[scraper.py, line 928 at r1](https://reviewable.io:443/reviews/m-lab/scraper/177#-KxFHAvKeGTolnGJyQNO:-KxJZuUVOHifo6wOoZ3A:b-8wleyk) ([raw file](https://github.com/m-lab/scraper/blob/f09a7801d426703d06c89c81191af151d6da31a2/scraper.py#L928)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Minor typo now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/177#-:-KxJ_1H1aMFVx0Moct7r:bnfp4nl)*

**Comment by gfr10598** [comment]
Reviewed 1 of 2 files at r2.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/177)*

**Comment by pboothe** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[scraper.py, line 928 at r1](https://reviewable.io:443/reviews/m-lab/scraper/177#-KxFHAvKeGTolnGJyQNO:-KxJeRfplB8X9mVMN6Y5:b-896fix) ([raw file](https://github.com/m-lab/scraper/blob/f09a7801d426703d06c89c81191af151d6da31a2/scraper.py#L928)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Minor typo now.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/177)*

**Pull request merged**
