### PR TITLE
Datastore

### PR DESCRIPTION
**Pull request by pboothe**
Moves the backing store for the date and whatnot to cloud datastore instead of the spreadsheet to get around spreadsheet API quota limits. A future PR will have the system that polls cloud datastore and uploads the results to the spreadsheet.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/scraper/16)

### CODE REVIEW

**Comment by gfr10598** [comment]
Review status: 0 of 7 files reviewed at latest revision, 8 unresolved discussions.

---

*[deploy.yml, line 1 at r2](https://reviewable.io:443/reviews/m-lab/scraper/16#-KezeutDAuiPBsn_iZaF:-KezeutDAuiPBsn_iZaG:b-ffvrhs) ([raw file](https://github.com/m-lab/scraper/blob/c7111af0ae6305594c7ab424b6e7ec4da776c7d4/deploy.yml#L1)):*
> ```YAML
> kind: Deployment
> ```

This deploy file presumes some other knowledge.  Could you add a one or two line header indicating what it is for, and maybe a link to reference material?

---

*[Dockerfile, line 14 at r2](https://reviewable.io:443/reviews/m-lab/scraper/16#-KezhBy2Upf4_VLGrOn2:-KezhBy353FSVFW1MEjj:bev4iua) ([raw file](https://github.com/m-lab/scraper/blob/c7111af0ae6305594c7ab424b6e7ec4da776c7d4/Dockerfile#L14)):*
> ```Dockerfile
> RUN chmod +x run_scraper.py
> # The monitoring port
> EXPOSE 9090
> ```

BTW, since you have the EXPOSE statement here, can you just use -P in the run command in README instead of -p 9090:9090 ?

---

*[run_scraper.py, line 135 at r2](https://reviewable.io:443/reviews/m-lab/scraper/16#-Kezhs3wwdSlRoykx2kB:-Kezhs3wwdSlRoykx2kC:b-stzptu) ([raw file](https://github.com/m-lab/scraper/blob/c7111af0ae6305594c7ab424b6e7ec4da776c7d4/run_scraper.py#L135)):*
> ```Python
>         type=str,
>         default='scraper',
>         help='The cloud datastore namespace to use in the current project. '
> ```

This help gives me a hint what I need to do if I run multiple scapers, but it isn't very clear.   What do I actually have to change?  Will I break things if I get it wrong?

---

*[scraper.py, line 477 at r2](https://reviewable.io:443/reviews/m-lab/scraper/16#-KezjF7_0mlTW5PgkSSG:-KezjF7_0mlTW5PgkSSH:b8wz2uq) ([raw file](https://github.com/m-lab/scraper/blob/c7111af0ae6305594c7ab424b6e7ec4da776c7d4/scraper.py#L477)):*
> ```Python
> 
> 
> class Status(object):
> ```

SyncStatus() ?

---

*[scraper.py, line 493 at r2](https://reviewable.io:443/reviews/m-lab/scraper/16#-Kezlc7uuEXjEaLloH8O:-KezjXdBwNY-jV_sEuBL:b15kinw) ([raw file](https://github.com/m-lab/scraper/blob/c7111af0ae6305594c7ab424b6e7ec4da776c7d4/scraper.py#L493)):*
> ```Python
>         self._entity = None
> 
>     def get_data(self):  # pragma: no cover
> ```

Add comment above explaining pragma, so it doesn't seem like cheating.  Better yet, get coverage for this by substituting _client in the init() call.

---

*[scraper.py, line 506 at r2](https://reviewable.io:443/reviews/m-lab/scraper/16#-Kezk6HnNk2Jq4_GprW8:-Kezk6HnNk2Jq4_GprW9:b-4v3jww) ([raw file](https://github.com/m-lab/scraper/blob/c7111af0ae6305594c7ab424b6e7ec4da776c7d4/scraper.py#L506)):*
> ```Python
>         """Returns the most recent date from which we have all the data.
> 
>         Downloads everything in the spreadsheet, then finds the right row, and
> ```

Comment needs updating?

---

*[scraper.py, line 531 at r2](https://reviewable.io:443/reviews/m-lab/scraper/16#-KezkekUXtAEXbsWD_tm:-KezkekUXtAEXbsWD_tn:bmcn3sq) ([raw file](https://github.com/m-lab/scraper/blob/c7111af0ae6305594c7ab424b6e7ec4da776c7d4/scraper.py#L531)):*
> ```Python
> 
>         Args:
>           entry_key: must be one of the header values
> ```

header no longer exists?  update comment?

---

*[scraper.py, line 548 at r2](https://reviewable.io:443/reviews/m-lab/scraper/16#-Kezkzrs6L4C4zq-NzbM:-Kezkzrs6L4C4zq-NzbN:b-gqxk5a) ([raw file](https://github.com/m-lab/scraper/blob/c7111af0ae6305594c7ab424b6e7ec4da776c7d4/scraper.py#L548)):*
> ```Python
> 
>     def update_debug_message(self, message):
>         """Updates the debug message on the spreadsheet."""
> ```

"spreadsheet" ?  Please update all comments where this word is used.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/16)*

**Comment by pboothe** [comment]
Review status: 0 of 9 files reviewed at latest revision, 7 unresolved discussions.

---

*[deploy.yml, line 1 at r2](https://reviewable.io:443/reviews/m-lab/scraper/16#-KezeutDAuiPBsn_iZaF:-Kf6xMVoxpyhZ7qRXScy:b-896fix) ([raw file](https://github.com/m-lab/scraper/blob/c7111af0ae6305594c7ab424b6e7ec4da776c7d4/deploy.yml#L1)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

This deploy file presumes some other knowledge.  Could you add a one or two line header indicating what it is for, and maybe a link to reference material?
</blockquote></details>

Done.

---

*[Dockerfile, line 14 at r2](https://reviewable.io:443/reviews/m-lab/scraper/16#-KezhBy2Upf4_VLGrOn2:-Kf6yy5YzHSBeaPdE7es:b-3z0b4q) ([raw file](https://github.com/m-lab/scraper/blob/c7111af0ae6305594c7ab424b6e7ec4da776c7d4/Dockerfile#L14)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

BTW, since you have the EXPOSE statement here, can you just use -P in the run command in README instead of -p 9090:9090 ?
</blockquote></details>

Not easily. Unfortunately `-P` exposes the service on a random port, and then `docker ports` is in charge of telling you the port-mapping. When you are running a single instance on your local machine, having the new service appear on a deterministic port is a feature.

---

*[run_scraper.py, line 135 at r2](https://reviewable.io:443/reviews/m-lab/scraper/16#-Kezhs3wwdSlRoykx2kB:-Kf73gQWLgN5Wq3yj149:b-higg85) ([raw file](https://github.com/m-lab/scraper/blob/c7111af0ae6305594c7ab424b6e7ec4da776c7d4/run_scraper.py#L135)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

This help gives me a hint what I need to do if I run multiple scapers, but it isn't very clear.   What do I actually have to change?  Will I break things if I get it wrong?
</blockquote></details>

Added info.

---

*[scraper.py, line 477 at r2](https://reviewable.io:443/reviews/m-lab/scraper/16#-KezjF7_0mlTW5PgkSSG:-Kf74sUVkGEqaC1ygvuv:bixmk0n) ([raw file](https://github.com/m-lab/scraper/blob/c7111af0ae6305594c7ab424b6e7ec4da776c7d4/scraper.py#L477)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

SyncStatus() ?
</blockquote></details>

A better name. Updated throughout.

---

*[scraper.py, line 493 at r2](https://reviewable.io:443/reviews/m-lab/scraper/16#-Kezlc7uuEXjEaLloH8O:-Kf7BuKdmk1mA8QZtuQ0:b484gte) ([raw file](https://github.com/m-lab/scraper/blob/c7111af0ae6305594c7ab424b6e7ec4da776c7d4/scraper.py#L493)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Add comment above explaining pragma, so it doesn't seem like cheating.  Better yet, get coverage for this by substituting _client in the init() call.
</blockquote></details>

Done. There isn't a lot of behavior to test, but I added test coverage.

---

*[scraper.py, line 506 at r2](https://reviewable.io:443/reviews/m-lab/scraper/16#-Kezk6HnNk2Jq4_GprW8:-Kf75KfelTvt5LwhMPm4:bb6un1j) ([raw file](https://github.com/m-lab/scraper/blob/c7111af0ae6305594c7ab424b6e7ec4da776c7d4/scraper.py#L506)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Comment needs updating?
</blockquote></details>

Done

---

*[scraper.py, line 531 at r2](https://reviewable.io:443/reviews/m-lab/scraper/16#-KezkekUXtAEXbsWD_tm:-Kf77EgEwunG6sl4m7sY:b-t9a9ri) ([raw file](https://github.com/m-lab/scraper/blob/c7111af0ae6305594c7ab424b6e7ec4da776c7d4/scraper.py#L531)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

header no longer exists?  update comment?
</blockquote></details>

the strings `header` and `spreadshee` no longer appear in any file.

---

*[scraper.py, line 548 at r2](https://reviewable.io:443/reviews/m-lab/scraper/16#-Kezkzrs6L4C4zq-NzbM:-Kf77PVGQWx6PlzQTKox:bb6un1j) ([raw file](https://github.com/m-lab/scraper/blob/c7111af0ae6305594c7ab424b6e7ec4da776c7d4/scraper.py#L548)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

"spreadsheet" ?  Please update all comments where this word is used.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/16)*

**Comment by pboothe** [comment]
PTAL

**Comment by gfr10598** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[deploy.yml, line 1 at r2](https://reviewable.io:443/reviews/m-lab/scraper/16#-KezeutDAuiPBsn_iZaF:-Kf7S-jx3lSL8U3fu86d:b-83sjoh) ([raw file](https://github.com/m-lab/scraper/blob/c7111af0ae6305594c7ab424b6e7ec4da776c7d4/deploy.yml#L1)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Nice!

---

*[scraper.py, line 493 at r2](https://reviewable.io:443/reviews/m-lab/scraper/16#-Kezlc7uuEXjEaLloH8O:-Kf7SfxK-kL6CWMTLHBu:b1x7bnq) ([raw file](https://github.com/m-lab/scraper/blob/c7111af0ae6305594c7ab424b6e7ec4da776c7d4/scraper.py#L493)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Done. There isn't a lot of behavior to test, but I added test coverage.
</blockquote></details>

Definitely agree.  I just prefer the model of injecting a mock object where it is straightforward.

---

*[scraper.py, line 477 at r3](https://reviewable.io:443/reviews/m-lab/scraper/16#-Kf7TLIcHY_oSx1DEz-K:-Kf7TLIdF5vyVX97ztrk:b-k5j4gv) ([raw file](https://github.com/m-lab/scraper/blob/f059e0819ca4bc8025848d60f1e1ea7c261d6777/scraper.py#L477)):*
> ```Python
> 
> 
> class SyncStatus(object):
> ```

Could you add a class comment and appropriate method comments, indicating what is blocking and what kind of failures might occur?  (I'll generally try to flag this kind of external dependency, and will appreciate if you do the same for (to?) me.  8-)

Possibly include the word "remote" in some of the names?

Hmm - as I think about it more, I wonder if this class deserves a short discussion about invariants and hazards.  In particular, it might be useful to call out that there are no protections or detection of concurrent read/write by separate processes, and refer to whatever mechanism is in place to avoid collisions.  Is there a risk of "zombie" processes colliding here?

---

*[scraper.py, line 503 at r3](https://reviewable.io:443/reviews/m-lab/scraper/16#-Kf7U8dSdVM_14Y-SnRO:-Kf7U8dSdVM_14Y-SnRP:bg22dp6) ([raw file](https://github.com/m-lab/scraper/blob/f059e0819ca4bc8025848d60f1e1ea7c261d6777/scraper.py#L503)):*
> ```Python
>         return self._client.get(self._key)
> 
>     def get_progress(self, default_date=datetime.date(2009, 1, 1)):
> ```

Seems like there should be a more informative name for this method, but good ideas are escaping me at the moment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/16)*

**Comment by pboothe** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[scraper.py, line 477 at r3](https://reviewable.io:443/reviews/m-lab/scraper/16#-Kf7TLIcHY_oSx1DEz-K:-Kf81V_bLZWalE0SGznp:burqd0u) ([raw file](https://github.com/m-lab/scraper/blob/f059e0819ca4bc8025848d60f1e1ea7c261d6777/scraper.py#L477)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Could you add a class comment and appropriate method comments, indicating what is blocking and what kind of failures might occur?  (I'll generally try to flag this kind of external dependency, and will appreciate if you do the same for (to?) me.  8-)

Possibly include the word "remote" in some of the names?

Hmm - as I think about it more, I wonder if this class deserves a short discussion about invariants and hazards.  In particular, it might be useful to call out that there are no protections or detection of concurrent read/write by separate processes, and refer to whatever mechanism is in place to avoid collisions.  Is there a risk of "zombie" processes colliding here?
</blockquote></details>

Added a class docstring discussing things.

---

*[scraper.py, line 503 at r3](https://reviewable.io:443/reviews/m-lab/scraper/16#-Kf7U8dSdVM_14Y-SnRO:-Kf8L3kwNOCZMXpcCr96:b-xvoffv) ([raw file](https://github.com/m-lab/scraper/blob/f059e0819ca4bc8025848d60f1e1ea7c261d6777/scraper.py#L503)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Seems like there should be a more informative name for this method, but good ideas are escaping me at the moment.
</blockquote></details>

"high water mark" and "progress" have been now uniformly named "last archived date".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/16)*

**Comment by gfr10598** [comment]
LGTM after suggested changes

---

Review status: 0 of 9 files reviewed at latest revision, 7 unresolved discussions.

---

*[run_scraper.py, line 137 at r5](https://reviewable.io:443/reviews/m-lab/scraper/16#-Kf8eZusOlhrDb2vMj0F:-Kf8eZutUbp6h19HSQrQ:b-c34gce) ([raw file](https://github.com/m-lab/scraper/blob/2a981b15f21a212e96ed53db20e30920b8363f5b/run_scraper.py#L137)):*
> ```Python
>         help='The cloud datastore namespace to use in the current project. '
>              'Every google cloud project has one datastore associated with '
>              'it. In order for us to run multiple scrapers within the same '
> ```

''' or """ ?

---

*[scraper.py, line 533 at r5](https://reviewable.io:443/reviews/m-lab/scraper/16#-Kf8fLbWzi6zPa4e5dHy:-Kf8fLbXfrK1ImQQFknQ:b-j77469) ([raw file](https://github.com/m-lab/scraper/blob/2a981b15f21a212e96ed53db20e30920b8363f5b/scraper.py#L533)):*
> ```Python
>         Used to determine what local data on a node has been archived and is
>         safe to delete, and also what data must be downloaded from a node, and
>         what data need not be downloaded.  It is expected that this quantity
> ```

I'd make this stronger than "expected".  Maybe "Other than exceptional recovery cases, this quantity *must* ..."

---

*[scraper.py, line 642 at r5](https://reviewable.io:443/reviews/m-lab/scraper/16#-Kf8gBM33poIeZ7jBw5x:-Kf8gBM4B4Te7wbtSVZw:b-tqmt9n) ([raw file](https://github.com/m-lab/scraper/blob/2a981b15f21a212e96ed53db20e30920b8363f5b/scraper.py#L642)):*
> ```Python
> 
> 
> def download(rsync_binary, rsync_url, status, destination):  # pragma: no cover
> ```

s/status/sync_status/

---

*[scraper.py, line 655 at r5](https://reviewable.io:443/reviews/m-lab/scraper/16#-Kf8gE7uUSyvRp5V4h8B:-Kf8gE7uUSyvRp5V4h8C:b5wxc0q) ([raw file](https://github.com/m-lab/scraper/blob/2a981b15f21a212e96ed53db20e30920b8363f5b/scraper.py#L655)):*
> ```Python
> 
> 
> def upload_if_allowed(args, status, destination,
> ```

s/status/sync_status

---

*[scraper.py, line 659 at r5](https://reviewable.io:443/reviews/m-lab/scraper/16#-Kf8gOhObk5MQ9SAWrjc:-Kf8gOhObk5MQ9SAWrjd:b582aag) ([raw file](https://github.com/m-lab/scraper/blob/2a981b15f21a212e96ed53db20e30920b8363f5b/scraper.py#L659)):*
> ```Python
>     """If enough time has passed, upload old data to GCS.
> 
>     Tar up what we have for each un-uploaded day that is sufficiently in the
> ```

s/un-uploaded/unarchived/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/16#-:-Kf8gqtw5sQvmHXQ47Sv:btc4463)*

**Comment by pboothe** [comment]
Use cloud datastore instead of a google spreadsheet

**Pull request merged**
