### PR TITLE
Keep production clean

### PR DESCRIPTION
**Pull request by pboothe**
Automatically delete old scrapers for machines or slices we no longer want to scrape.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/scraper/86)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
:lgtm:  Just some requests for clarifying comments.

---

Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[deploy.sh, line 147 at r4](https://reviewable.io:443/reviews/m-lab/scraper/86#-Knp0rvU5j9tcllc6lPH:-Knp0rvVdzfdHl2-dYOS:bf11h84) ([raw file](https://github.com/m-lab/scraper/blob/7f2c8d63da39fe3858948964252989899b1d132c/deploy.sh#L147)):*
> ```Shell
>   > ${DESIRED_DEPLOYMENTS}
> # To delete stuff either takes way too long, or requires using the kubectl proxy
> # to set things using curl that are unsettable in the CLI client.
> ```

nit: please phrase as something like "requires using curl via kubectl proxy to access features not yet supported by kubectl cli client". This implies a time when we may be able to remove the dependency on the proxy.

Adding a todo for that would also be welcome.

---

*[deploy.sh, line 157 at r4](https://reviewable.io:443/reviews/m-lab/scraper/86#-Knp1TNr1pi99Vqo5Ubb:-Knp1TNr1pi99Vqo5Ubc:bra81os) ([raw file](https://github.com/m-lab/scraper/blob/7f2c8d63da39fe3858948964252989899b1d132c/deploy.sh#L157)):*
> ```Shell
>   | while read DEPLOY; do
>       # We wish we could just:
>       #   kubectl -n scraper delete deploy/${DEPLOY} --now --force
> ```

Is this the form the command will take when kubectl supports the "deleteoptions" natively? If so, please call that out.

---

*[deploy.sh, line 164 at r4](https://reviewable.io:443/reviews/m-lab/scraper/86#-Knp1jCfzuPee5BMP_AQ:-Knp1jCfzuPee5BMP_AR:b-58x2cr) ([raw file](https://github.com/m-lab/scraper/blob/7f2c8d63da39fe3858948964252989899b1d132c/deploy.sh#L164)):*
> ```Shell
>         -H "Content-Type: application/json"
>       # This only deletes one thing, rather than recursively deleting many
>       # things, so this should still work.
> ```

So this "should still work [relatively quickly]"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/86#-:-Knp1wwZhjd98zKC9OPG:bhhcoo4)*

**Comment by pboothe** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[deploy.sh, line 147 at r4](https://reviewable.io:443/reviews/m-lab/scraper/86#-Knp0rvU5j9tcllc6lPH:-KnpKpnmaVcBGaaA_azJ:b-896fix) ([raw file](https://github.com/m-lab/scraper/blob/7f2c8d63da39fe3858948964252989899b1d132c/deploy.sh#L147)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

nit: please phrase as something like "requires using curl via kubectl proxy to access features not yet supported by kubectl cli client". This implies a time when we may be able to remove the dependency on the proxy.

Adding a todo for that would also be welcome.
</blockquote></details>

Done.

---

*[deploy.sh, line 157 at r4](https://reviewable.io:443/reviews/m-lab/scraper/86#-Knp1TNr1pi99Vqo5Ubb:-KnpKqAA7JLDMPUBsiTG:b-896fix) ([raw file](https://github.com/m-lab/scraper/blob/7f2c8d63da39fe3858948964252989899b1d132c/deploy.sh#L157)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Is this the form the command will take when kubectl supports the "deleteoptions" natively? If so, please call that out.
</blockquote></details>

Done.

---

*[deploy.sh, line 164 at r4](https://reviewable.io:443/reviews/m-lab/scraper/86#-Knp1jCfzuPee5BMP_AQ:-KnpKqhj7mHazGORz7pD:b-896fix) ([raw file](https://github.com/m-lab/scraper/blob/7f2c8d63da39fe3858948964252989899b1d132c/deploy.sh#L164)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

So this "should still work [relatively quickly]"?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/86)*

**Comment by stephen-soltesz** [comment]
Reviewed 1 of 1 files at r4.
Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/86)*

**Comment by stephen-soltesz** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper/86)*

**Pull request merged**
